DTStack/chunjun

README.md

Laucher.java 重复代码造成任务重复执行

---

flinkx-test/pom.xml

```xml
<dependency>
<groupId>com.dtstack.flinkx</groupId>
<artifactId>flinkx-rdb-core</artifactId>
<version>1.6</version>
</dependency>
```

移除重复的依赖flinkx-rdb-core

---

flinkx-stream/flinkx-stream-writer/src/main/java/com/dtstack/flinkx/stream/writer/StreamOutputFormat.java
flinkx-stream/flinkx-stream-writer/src/main/java/com/dtstack/flinkx/stream/writer/StreamOutputFormatBuilder.java
flinkx-stream/flinkx-stream-writer/src/main/java/com/dtstack/flinkx/stream/writer/StreamWriter.java

streamWriter supports batch writing and custom delimiter

streamWriter supports batch writing and custom delimiter

---

docs/pulsarwriter.md
flinkx-pulsar/flinkx-pulsar-writer/pom.xml
flinkx-pulsar/flinkx-pulsar-writer/src/main/java/com/dtstack/flinkx/pulsar/writer/Constants.java
flinkx-pulsar/flinkx-pulsar-writer/src/main/java/com/dtstack/flinkx/pulsar/writer/PulsarOutputFormat.java
flinkx-pulsar/flinkx-pulsar-writer/src/main/java/com/dtstack/flinkx/pulsar/writer/PulsarOutputFormatBuilder.java
flinkx-pulsar/flinkx-pulsar-writer/src/main/java/com/dtstack/flinkx/pulsar/writer/PulsarWriter.java
flinkx-pulsar/flinkx-pulsar-writer/src/main/java/com/dtstack/flinkx/pulsar/writer/decoder/IDecode.java
flinkx-pulsar/flinkx-pulsar-writer/src/main/java/com/dtstack/flinkx/pulsar/writer/decoder/JsonDecoder.java
flinkx-pulsar/flinkx-pulsar-writer/src/main/java/com/dtstack/flinkx/pulsar/writer/decoder/PlainDecoder.java
flinkx-pulsar/pom.xml
pom.xml

> Apache Pulsar is an open-source distributed pub-sub messaging system originally created at Yahoo and now part of the Apache Software Foundation
Add a simple pulsar writer.

A simple pulsar writer

---

flinkx-core/src/main/java/com/dtstack/flinkx/inputformat/BaseRichInputFormat.java
flinkx-core/src/main/java/com/dtstack/flinkx/outputformat/BaseRichOutputFormat.java
flinkx-hive/flinkx-hive-writer/src/main/java/com/dtstack/flinkx/hive/writer/HiveOutputFormat.java

see https://github.com/DTStack/flinkx/pull/255

fix bytewrite metric

---

docs/quickstart.md
flinkx-hdfs/flinkx-hdfs-core/src/main/java/com/dtstack/flinkx/hdfs/ECompressType.java
flinkx-hdfs/flinkx-hdfs-writer/pom.xml
flinkx-hdfs/flinkx-hdfs-writer/src/main/java/com/dtstack/flinkx/hdfs/writer/HdfsTextOutputFormat.java

flinkx-hdfs/flinkx-hdfs-core/src/main/java/com/dtstack/flinkx/hdfs/ECompressType.java
add enum properties for lzo
flinkx-hdfs/flinkx-hdfs-writer/pom.xml
add dependency for lzo
flinkx-hdfs/flinkx-hdfs-writer/src/main/java/com/dtstack/flinkx/hdfs/writer/HdfsTextOutputFormat.java
add code for lzo

add lzo conpress for hdfs wtire with text type

---

flinkx-postgresql/flinkx-postgresql-core/src/main/java/com/dtstack/flinkx/postgresql/PostgresqlDatabaseMeta.java

postgresql支持update增量更新操作，需要指定updateKey，如果联合唯一索引key为数组， "updateKey": {"key":["id","name"]}
`{
"job" : {
"content" : [ {
"reader" : {
"parameter" : {
"codec": "json",
"groupId" : "user",
"topic" : "user",
"consumerSettings" : {
"zookeeper.connect" : "xxx:2181,xxx:2181,xxx:2181",
"bootstrap.servers" : "xxx:9092,xxx:9092,xxx:9092,xxx:9092",
"auto.commit.interval.ms" : "1000",
"auto.offset.reset" : "earliest"
},
"column": [
{"name": "name", "type": "varchar"},
{"name": "id", "type": "bigint"}
]
},
"name" : "kafkareader"
},
"writer": {
"name": "postgresqlwriter",
"parameter": {
"username": "xxx",
"password": "xxxx",
"batchSize": 1,
"connection": [
{
"jdbcUrl": "jdbc:postgresql://192.xx.xxx.xx:5432/postgres",
"table": [
"user"
]
}
],
"session": [],
"preSql": [],
"postSql": [],
"writeMode": …

postgresql支持update增量更新操作

---

README.md
README_CH.md
docs/restore.md

readme文件拼写错误

---

README.md

Just a trivial patch for syntax.

[doc] Update readme.md: Corrct the syntax format

---

flinkx-test/src/main/java/com/dtstack/flinkx/test/LocalTest.java

[fix]replace job path

---

flinkx-pulsar/flinkx-pulsar-reader/pom.xml
flinkx-pulsar/flinkx-pulsar-reader/src/main/java/com/dtstack/flinkx/pulsar/client/FlinkxPulsarClient.java
flinkx-pulsar/flinkx-pulsar-reader/src/main/java/com/dtstack/flinkx/pulsar/client/FlinkxPulsarConsumer.java
flinkx-pulsar/flinkx-pulsar-reader/src/main/java/com/dtstack/flinkx/pulsar/format/Constants.java
flinkx-pulsar/flinkx-pulsar-reader/src/main/java/com/dtstack/flinkx/pulsar/format/PulsarInputFormat.java
flinkx-pulsar/flinkx-pulsar-reader/src/main/java/com/dtstack/flinkx/pulsar/format/PulsarInputFormatBuilder.java
flinkx-pulsar/flinkx-pulsar-reader/src/main/java/com/dtstack/flinkx/pulsar/reader/PulsarReader.java
flinkx-pulsar/pom.xml
flinkx-test/pom.xml
flinkx-test/src/main/java/com/dtstack/flinkx/test/LocalTest.java
flinkx-test/src/main/java/com/dtstack/flinkx/test/PluginNameConstants.java

[feat-354] [pulsar]增加pulsar reader插件

[feat-354] [pulsar]增加pulsar reader插件

---

docs/quickstart.md

[fix-387][logminer][docs] add standaLoneQuickStart docs

---

docs/realTime/reader/pulsarreader.md
flinkx-pulsar/flinkx-pulsar-reader/src/main/java/com/dtstack/flinkx/pulsar/client/FlinkxPulsarClient.java
flinkx-pulsar/flinkx-pulsar-reader/src/main/java/com/dtstack/flinkx/pulsar/format/PulsarInputFormat.java
flinkx-pulsar/flinkx-pulsar-reader/src/main/java/com/dtstack/flinkx/pulsar/format/PulsarInputFormatBuilder.java
flinkx-pulsar/flinkx-pulsar-reader/src/main/java/com/dtstack/flinkx/pulsar/reader/PulsarReader.java
flinkx-test/pom.xml
flinkx-test/src/main/java/com/dtstack/flinkx/test/LocalTest.java
flinkx-test/src/main/java/com/dtstack/flinkx/test/PluginNameConstants.java

1.修改Pulsar-reader参数，支持Pulsar原生loadConf配置。
2.修改Pulsar-reader文档，增加pulsar2pulsar例子。

[flinkx-#385][pulsar-reader] 修改Pulsar-reader参数

---

docs/iceberg.md

correct document link for iceberg

correct document link for iceberg

---

docs/connectors/elasticsearch6/es6lookup.md
docs/connectors/elasticsearch6/es6reader.md
docs/connectors/elasticsearch6/es6writer.md
docs/iceberg.md
docs/quickstart.md
flinkx-connectors/flinkx-connector-elasticsearch6/pom.xml
flinkx-connectors/flinkx-connector-elasticsearch6/src/main/java/com/dtstack/flinkx/connector/es/conf/EsConf.java
flinkx-connectors/flinkx-connector-elasticsearch6/src/main/java/com/dtstack/flinkx/connector/es/converter/EsColumnConverter.java
flinkx-connectors/flinkx-connector-elasticsearch6/src/main/java/com/dtstack/flinkx/connector/es/converter/EsRowConverter.java
flinkx-connectors/flinkx-connector-elasticsearch6/src/main/java/com/dtstack/flinkx/connector/es/source/EsDynamicTableSource.java
flinkx-connectors/flinkx-connector-elasticsearch6/src/main/java/com/dtstack/flinkx/connector/es/source/EsInputFormat.java
flinkx-connectors/flinkx-connector-elasticsearch6/src/main/java/com/dtstack/flinkx/connector/es/source/EsSourceFactory.java
flinkx-connectors/flinkx-connector-elasticsearch6/src/main/java/com/dtstack/flinkx/connector/es/utils/EsConstants.java
flinkx-examples/sql/elasticsearch6/es2es.sql
flinkx-examples/sql/elasticsearch6/kafka_eslookup_stream.sql

1.modified the es connector name for sql job type.
2. fix bug https://github.com/DTStack/flinkx/issues/451
3. update es doc.

Hotfix 449

---

flinkx-pulsar/flinkx-pulsar-reader/src/main/java/com/dtstack/flinkx/pulsar/client/FlinkxPulsarClient.java
flinkx-pulsar/flinkx-pulsar-reader/src/main/java/com/dtstack/flinkx/pulsar/format/Constants.java
flinkx-pulsar/flinkx-pulsar-reader/src/main/java/com/dtstack/flinkx/pulsar/format/PulsarInputFormat.java
flinkx-pulsar/flinkx-pulsar-reader/src/main/java/com/dtstack/flinkx/pulsar/format/PulsarInputFormatBuilder.java
flinkx-pulsar/flinkx-pulsar-reader/src/main/java/com/dtstack/flinkx/pulsar/reader/PulsarReader.java
flinkx-pulsar/pom.xml

[feat-535] [flinkx-pulsar]升级Pulsar客户端版本

---

flinkx-core/src/main/java/com/dtstack/flinkx/constants/ConstantValue.java
flinkx-oss/flinkx-oss-core/pom.xml
flinkx-oss/flinkx-oss-core/src/main/java/com/dtstack/flinkx/oss/ECompressType.java
flinkx-oss/flinkx-oss-core/src/main/java/com/dtstack/flinkx/oss/OssConfigKeys.java
flinkx-oss/flinkx-oss-core/src/main/java/com/dtstack/flinkx/oss/OssUtil.java
flinkx-oss/flinkx-oss-core/src/main/java/com/dtstack/flinkx/oss/util/StrUtil.java
flinkx-oss/flinkx-oss-core/src/main/java/org/apache/hadoop/hive/shims/ShimLoader.java
flinkx-oss/flinkx-oss-writer/pom.xml
flinkx-oss/flinkx-oss-writer/src/main/java/com/dtstack/flinkx/oss/writer/BaseOssOutputFormat.java
flinkx-oss/flinkx-oss-writer/src/main/java/com/dtstack/flinkx/oss/writer/OssOutputFormatBuilder.java
flinkx-oss/flinkx-oss-writer/src/main/java/com/dtstack/flinkx/oss/writer/OssTextOutputFormat.java
flinkx-oss/flinkx-oss-writer/src/main/java/com/dtstack/flinkx/oss/writer/OssWriter.java
flinkx-oss/pom.xml
pom.xml

[feat-553][oss] 增加实现oss-writer

---

flinkx-core/src/main/java/com/dtstack/flinkx/constants/ConstantValue.java
flinkx-oss/flinkx-oss-core/pom.xml
flinkx-oss/flinkx-oss-core/src/main/java/com/dtstack/flinkx/oss/ECompressType.java
flinkx-oss/flinkx-oss-core/src/main/java/com/dtstack/flinkx/oss/OssConfigKeys.java
flinkx-oss/flinkx-oss-core/src/main/java/com/dtstack/flinkx/oss/OssUtil.java
flinkx-oss/flinkx-oss-core/src/main/java/com/dtstack/flinkx/oss/util/StrUtil.java
flinkx-oss/flinkx-oss-core/src/main/java/org/apache/hadoop/hive/shims/ShimLoader.java
flinkx-oss/flinkx-oss-writer/pom.xml
flinkx-oss/flinkx-oss-writer/src/main/java/com/dtstack/flinkx/oss/writer/BaseOssOutputFormat.java
flinkx-oss/flinkx-oss-writer/src/main/java/com/dtstack/flinkx/oss/writer/OssOutputFormatBuilder.java
flinkx-oss/flinkx-oss-writer/src/main/java/com/dtstack/flinkx/oss/writer/OssTextOutputFormat.java
flinkx-oss/flinkx-oss-writer/src/main/java/com/dtstack/flinkx/oss/writer/OssWriter.java
flinkx-oss/pom.xml
flinkx-test/src/main/java/com/dtstack/flinkx/test/LocalTest.java
flinkx-test/src/main/java/com/dtstack/flinkx/test/PluginNameConstants.java
pom.xml

[feat-556][test] 增加实现对于oss-writer的测试案例

---

docs/realTime/writer/hudiwriter.md

[docs-554][flinkx-hudi] 增加kafka写入hudi实例文档

---

flinkx-pulsar/flinkx-pulsar-reader/src/main/java/com/dtstack/flinkx/pulsar/client/FlinkxPulsarClient.java
flinkx-pulsar/flinkx-pulsar-reader/src/main/java/com/dtstack/flinkx/pulsar/format/Constants.java
flinkx-pulsar/flinkx-pulsar-reader/src/main/java/com/dtstack/flinkx/pulsar/format/PulsarInputFormat.java
flinkx-pulsar/flinkx-pulsar-reader/src/main/java/com/dtstack/flinkx/pulsar/format/PulsarInputFormatBuilder.java
flinkx-pulsar/flinkx-pulsar-reader/src/main/java/com/dtstack/flinkx/pulsar/reader/PulsarReader.java

[feat-535] [flinkx-pulsar]增加Pulsar批量拉取配置项

---

flinkx-alluxio/flinkx-alluxio-core/pom.xml
flinkx-alluxio/flinkx-alluxio-core/src/main/java/com/dtstack/flinkx/alluxio/AlluxioConfigKeys.java
flinkx-alluxio/flinkx-alluxio-core/src/main/java/com/dtstack/flinkx/alluxio/AlluxioUtil.java
flinkx-alluxio/flinkx-alluxio-core/src/main/java/com/dtstack/flinkx/alluxio/ECompressType.java
flinkx-alluxio/flinkx-alluxio-core/src/main/java/com/dtstack/flinkx/alluxio/util/StringUtil.java
flinkx-alluxio/flinkx-alluxio-writer/pom.xml
flinkx-alluxio/flinkx-alluxio-writer/src/main/java/com/dtstack/flinkx/alluxio/writer/AlluxioOrcOutputFormat.java
flinkx-alluxio/flinkx-alluxio-writer/src/main/java/com/dtstack/flinkx/alluxio/writer/AlluxioOutputFormatBuilder.java
flinkx-alluxio/flinkx-alluxio-writer/src/main/java/com/dtstack/flinkx/alluxio/writer/AlluxioParquetOutputFormat.java
flinkx-alluxio/flinkx-alluxio-writer/src/main/java/com/dtstack/flinkx/alluxio/writer/AlluxioTextOutputFormat.java
flinkx-alluxio/flinkx-alluxio-writer/src/main/java/com/dtstack/flinkx/alluxio/writer/AlluxioWriter.java
flinkx-alluxio/flinkx-alluxio-writer/src/main/java/com/dtstack/flinkx/alluxio/writer/BaseAlluxioOutputFormat.java
flinkx-alluxio/pom.xml
flinkx-core/src/main/java/com/dtstack/flinkx/constants/ConstantValue.java
flinkx-core/src/main/java/com/dtstack/flinkx/enums/WriteType.java
flinkx-test/pom.xml
flinkx-test/src/main/java/com/dtstack/flinkx/test/LocalTest.java
flinkx-test/src/main/java/com/dtstack/flinkx/test/PluginNameConstants.java
pom.xml

[feat-570][flinkx-alluxio] 增加flinkx-alluxio-writer模块

---

README.md
README_EN.md
docs/offline/writer/alluxiowriter.md

增加stream写入alluxio实例文档

---

docs/quickstart.md

fix(doc): fix doc

---

flinkx-connectors/flinkx-connector-postgresql/src/main/java/com/dtstack/flinkx/connector/postgresql/dialect/PostgresqlDialect.java

fix conflict key has not been filtered.

fix postgre jdbc upsert mode has not been filtered primary key.

---

flinkx-connectors/flinkx-connector-jdbc-base/src/main/java/com/dtstack/flinkx/connector/jdbc/sink/JdbcOutputFormat.java

Reverts DTStack/chunjun#623
transaction commit in the function commit()

Revert "fix[#622] jdbc connection in exact_once mode forget commit transaction."

---

flinkx-core/src/main/java/com/dtstack/flinkx/sql/FunctionManager.java

fix udf anonation @FunctionHint and @DataTypeHint don' work.

[hotfix-620][core] udf anonation @FunctionHint and @DataTypeHint don' work.

---

bin/install_jars.bat

Add maven command of installing the jar of ticdc-decoder
issue #663

[issue-663][bin/install_jars.bat] Add maven command of installing the jar of ticdc-decoder

---

flinkx-connectors/flinkx-connector-jdbc-base/src/main/java/com/dtstack/flinkx/connector/jdbc/sink/JdbcOutputFormatBuilder.java
flinkx-connectors/flinkx-connector-jdbc-base/src/main/java/com/dtstack/flinkx/connector/jdbc/source/JdbcInputFormatBuilder.java
flinkx-connectors/flinkx-connector-jdbc-base/src/main/java/com/dtstack/flinkx/connector/jdbc/table/JdbcDynamicTableFactory.java

[issue-668][jdbc] Support mysql root without password.
issue #668

[issue-668][jdbc] Support mysql root without password.

---

bin/install_jars.bat
bin/install_jars.sh

Add inceptor-driver-6.0.2.jar and add the command of maven-install.
For issue #674

[issue-674][jars] Add inceptor-driver-6.0.2.jar and add the command of maven-install

---

flinkx-connectors/flinkx-connector-jdbc-base/src/main/java/com/dtstack/flinkx/connector/jdbc/conf/JdbcConf.java
flinkx-connectors/flinkx-connector-jdbc-base/src/main/java/com/dtstack/flinkx/connector/jdbc/source/JdbcInputFormat.java
flinkx-connectors/flinkx-connector-jdbc-base/src/main/java/com/dtstack/flinkx/connector/jdbc/source/JdbcSourceFactory.java
flinkx-core/src/main/java/com/dtstack/flinkx/util/ColumnBuildUtil.java

解决myql 使用customSql参数一些相关bug
https://github.com/DTStack/chunjun/issues/672

[hotfix-#672][jdbc] 修复mysql读取使用自定义customSql参数时遇到的相关bug 

---

flinkx-docker/docker/Dockerfile

[issue-677][docker]修改镜像中的flink版本

---

docs/questions.md
flinkx-connectors/flinkx-connector-jdbc-base/src/main/java/com/dtstack/flinkx/connector/jdbc/source/JdbcInputFormat.java
flinkx-connectors/flinkx-connector-jdbc-base/src/main/java/com/dtstack/flinkx/connector/jdbc/source/JdbcSourceFactory.java

编译报错补充文档，resolve build error: failed to read artifact descriptor for com.google.errorprone:javac-shaded
https://github.com/DTStack/chunjun/issues/609

[issue-609][docs] resolve build error: failed to read artifact descriptor for com.google.errorprone:javac-shaded

---

flinkx-connectors/flinkx-connector-sqlservercdc/src/main/java/com/dtstack/flinkx/connector/sqlservercdc/convert/SqlServerCdcColumnConverter.java

[hotfix-739][flinkx-connectors] SQLserver cdc同步过程中，smallint类型的数据同步报错

[hotfix-739][flinkx-connectors] SQLserver cdc增加对数据类型smallint的支持

---

flinkx-connectors/flinkx-connector-clickhouse/src/main/java/com/dtstack/flinkx/connector/clickhouse/converter/ClickhouseRawTypeConverter.java

Fixed clickHouse not supporting Decimal types with precision and scale  #647

[hotfix-647][clickhouse]decimal type supports precision

---

flinkx-connectors/flinkx-connector-oceanbase/pom.xml
flinkx-connectors/flinkx-connector-oceanbase/src/main/java/com/dtstack/flinkx/connector/oceanbase/converter/OceanbaseRawTypeConverter.java
flinkx-connectors/flinkx-connector-oceanbase/src/main/java/com/dtstack/flinkx/connector/oceanbase/dialect/OceanbaseDialect.java
flinkx-connectors/flinkx-connector-oceanbase/src/main/java/com/dtstack/flinkx/connector/oceanbase/sink/OceanbaseSinkFactory.java
flinkx-connectors/flinkx-connector-oceanbase/src/main/java/com/dtstack/flinkx/connector/oceanbase/source/OceanbaseSourceFactory.java
flinkx-connectors/flinkx-connector-oceanbase/src/main/java/com/dtstack/flinkx/connector/oceanbase/table/OceanbaseDynamicTableFactory.java
flinkx-connectors/flinkx-connector-oceanbase/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
flinkx-connectors/pom.xml
flinkx-local-test/pom.xml

[feat-760][oceanbase]support oceanbase mysql tenant connector

[feat-760][oceanbase]support oceanbase mysql tenant connector

---

flinkx-clients/src/main/java/com/dtstack/flinkx/client/Launcher.java
flinkx-connectors/flinkx-connector-hdfs/src/main/java/com/dtstack/flinkx/connector/hdfs/sink/HdfsOrcOutputFormat.java
flinkx-core/src/main/java/com/dtstack/flinkx/conf/FlinkxCommonConf.java
flinkx-core/src/main/java/com/dtstack/flinkx/conf/MetricPluginConf.java
flinkx-core/src/main/java/com/dtstack/flinkx/metrics/RowSizeCalculator.java
flinkx-core/src/main/java/com/dtstack/flinkx/sink/format/BaseRichOutputFormat.java
flinkx-core/src/main/java/com/dtstack/flinkx/source/format/BaseRichInputFormat.java
flinkx-core/src/main/java/com/dtstack/flinkx/util/PropertiesUtil.java

1.Determine whether the JDK allows ObjectCalculator 2.add undoCalculator(return 0 when calculate rowData size). config by MetricPluginConf#rowSizeCalculatorType
#788

[hotfix-788][metric]row size calculator optimize

---

chunjun-core/src/main/java/com/dtstack/chunjun/enums/ColumnType.java

jdbc numberType contain all numeric type
#826

[hotfix-435][jdbc]jdbc numberType contain all numeric type

---

chunjun-core/src/main/java/com/dtstack/chunjun/enums/ColumnType.java

add missing columnType TIMESTAMPZ

[hotfix-853][columnType]add columnType TIMESTAMPZ

---

chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/sink/DorisSinkFactory.java
chunjun-core/src/main/java/com/dtstack/chunjun/mapping/NameMappingConf.java
chunjun-core/src/main/java/com/dtstack/chunjun/mapping/NameMappingFlatMap.java

the issue address is [859](https://github.com/DTStack/chunjun/issues/859)

Fix NPE when NameMapping is empty.

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/sink/PreparedStmtProxy.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/statement/FieldNamedPreparedStatement.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/statement/FieldNamedPreparedStatementImpl.java
chunjun-connectors/chunjun-connector-postgresql/src/main/java/com/dtstack/chunjun/connector/postgresql/converter/PostgresqlColumnConverter.java
chunjun-connectors/chunjun-connector-postgresql/src/main/java/com/dtstack/chunjun/connector/postgresql/converter/PostgresqlRawTypeConverter.java
chunjun-connectors/chunjun-connector-postgresql/src/main/java/com/dtstack/chunjun/connector/postgresql/dialect/PostgresqlDialect.java
chunjun-connectors/chunjun-connector-postgresql/src/main/java/com/dtstack/chunjun/connector/postgresql/sink/PostgresOutputFormat.java
chunjun-core/src/main/java/com/dtstack/chunjun/element/column/ArrayColumn.java

the issue address is [875](https://github.com/DTStack/chunjun/issues/875)

postgresql sync support array type.

---

chunjun-formats/chunjun-protobuf/src/test/java/com/dtstack/chunjun/format/protobuf/test/MessageTestOuterClass.java

Format code with command 'mvn spotless:apply'.

[hotfix-889][Test] Fix chunjun package failed.

---

chunjun-connectors/chunjun-connector-binlog/pom.xml

主要原因就是binlog模块里的guava与用户集群里的版本冲突, 导致报错
https://github.com/DTStack/chunjun/issues/820

[hotfix-820][binlog] Fixed Canal Parse Exception

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcInputFormat.java

1.Fixed loss of endLocation when recovering from checkpoint/savepoint 
2.Fix startLocation lost when endLocation is not empty
#919

[hotfix-#919][jdbc] fix issue of startLocation/endLocation was mistakenly lost

---

chunjun-clients/src/main/java/com/dtstack/chunjun/client/yarn/YarnSessionClusterClientHelper.java

Clear userArtifact, userJar, classpath for JobGraph in session job
#953

[hotfix-#953][session]Fix the session job startup failure

---

docs_zh/ChunJun 通用配置详解.md
docs_zh/ChunJun连接器/hdfs/hdfs-sink.md
docs_zh/ChunJun连接器/hdfs/hdfs-source.md
docs_zh/ChunJun连接器/kudu/kudu-sink.md
docs_zh/ChunJun连接器/kudu/kudu-source.md

[docs][common] format common documents.
[docs][kudu] modify kudu source and sink documents.
[docs][kudu] modify kudu source and sink documents.

Master doc format

---

chunjun-connectors/chunjun-connector-kafka/src/main/java/com/dtstack/chunjun/connector/kafka/converter/KafkaColumnConverter.java
chunjun-core/src/main/java/com/dtstack/chunjun/source/SourceFactory.java

Fix sync task of kafka throws npe.
Fixes # (1063).

[hotfix-#1063][kafka] Fix sync Task of kafka throws npe.

---

chunjun-connectors/chunjun-connector-cassandra/src/main/java/com/dtstack/chunjun/connector/cassandra/sink/CassandraOutputFormatBuilder.java
chunjun-connectors/chunjun-connector-clickhouse/src/main/java/com/dtstack/chunjun/connector/clickhouse/sink/ClickhouseOutputFormatBuilder.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/sink/DorisHttpOutputFormatBuilder.java
chunjun-connectors/chunjun-connector-elasticsearch6/src/main/java/com/dtstack/chunjun/connector/elasticsearch6/sink/Elasticsearch6OutputFormatBuilder.java
chunjun-connectors/chunjun-connector-elasticsearch7/src/main/java/com/dtstack/chunjun/connector/elasticsearch7/sink/ElasticsearchOutputFormatBuilder.java
chunjun-connectors/chunjun-connector-emqx/src/main/java/com/dtstack/chunjun/connector/emqx/sink/EmqxOutputFormatBuilder.java
chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/sink/FtpOutputFormatBuilder.java
chunjun-connectors/chunjun-connector-hbase-1.4/src/main/java/com/dtstack/chunjun/connector/hbase14/sink/HBaseOutputFormatBuilder.java
chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/sink/HdfsDynamicTableSink.java
chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/sink/HdfsOutputFormatBuilder.java
chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/sink/HdfsSinkFactory.java
chunjun-connectors/chunjun-connector-hive/src/main/java/com/dtstack/chunjun/connector/hive/sink/HiveOutputFormat.java
chunjun-connectors/chunjun-connector-hive/src/main/java/com/dtstack/chunjun/connector/hive/sink/HiveOutputFormatBuilder.java
chunjun-connectors/chunjun-connector-http/src/main/java/com/dtstack/chunjun/connector/http/outputformat/HttpOutputFormatBuilder.java
chunjun-connectors/chunjun-connector-inceptor/src/main/java/com/dtstack/chunjun/connector/inceptor/sink/InceptorFileOutputFormatBuilder.java
chunjun-connectors/chunjun-connector-inceptor/src/main/java/com/dtstack/chunjun/connector/inceptor/sink/InceptorFileSinkFactory.java
chunjun-connectors/chunjun-connector-influxdb/src/main/java/com/dtstack/chunjun/connector/influxdb/sink/InfluxdbOutputFormatBuilder.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/sink/JdbcOutputFormatBuilder.java
chunjun-connectors/chunjun-connector-kudu/src/main/java/com/dtstack/chunjun/connector/kudu/sink/KuduOutputFormatBuilder.java
chunjun-connectors/chunjun-connector-mongodb/src/main/java/com/dtstack/chunjun/connector/mongodb/sink/MongodbOutputFormatBuilder.java
chunjun-connectors/chunjun-connector-mongodb/src/main/java/com/dtstack/chunjun/connector/mongodb/sink/MongodbSinkFactory.java
chunjun-connectors/chunjun-connector-mongodb/src/main/java/com/dtstack/chunjun/connector/mongodb/table/MongodbDynamicTableSink.java
chunjun-connectors/chunjun-connector-redis/src/main/java/com/dtstack/chunjun/connector/redis/sink/RedisOutputFormatBuilder.java
chunjun-connectors/chunjun-connector-solr/src/main/java/com/dtstack/chunjun/connector/solr/sink/SolrOutputFormatBuilder.java
chunjun-connectors/chunjun-connector-stream/src/main/java/com/dtstack/chunjun/connector/stream/sink/StreamOutputFormatBuilder.java
chunjun-core/src/main/java/com/dtstack/chunjun/sink/format/BaseRichOutputFormatBuilder.java
chunjun-core/src/main/java/com/dtstack/chunjun/sink/format/FileOutputFormatBuilder.java

Optimize the inheritance of 'BaseRichOutputFormat'.
Fixes # (1077).

[feat-#1077][base] Optimize the inheritance of 'BaseRichOutputFormat'.

---

docs/quickstart.md

Repeat keyword “jobType”

---

chunjun-connectors/chunjun-connector-redis/src/main/java/com/dtstack/chunjun/connector/redis/connection/RedisSyncClient.java
chunjun-connectors/chunjun-connector-redis/src/main/java/com/dtstack/chunjun/connector/redis/converter/RedisColumnConverter.java
chunjun-connectors/chunjun-connector-redis/src/main/java/com/dtstack/chunjun/connector/redis/converter/RedisRawTypeConverter.java
chunjun-connectors/chunjun-connector-redis/src/main/java/com/dtstack/chunjun/connector/redis/inputsplit/RedisInputSplit.java
chunjun-connectors/chunjun-connector-redis/src/main/java/com/dtstack/chunjun/connector/redis/lookup/RedisAllTableFunction.java
chunjun-connectors/chunjun-connector-redis/src/main/java/com/dtstack/chunjun/connector/redis/options/RedisOptions.java
chunjun-connectors/chunjun-connector-redis/src/main/java/com/dtstack/chunjun/connector/redis/source/RedisDynamicTableSource.java
chunjun-connectors/chunjun-connector-redis/src/main/java/com/dtstack/chunjun/connector/redis/source/RedisInputFormat.java
chunjun-connectors/chunjun-connector-redis/src/main/java/com/dtstack/chunjun/connector/redis/source/RedisInputFormatBuilder.java
chunjun-connectors/chunjun-connector-redis/src/main/java/com/dtstack/chunjun/connector/redis/source/RedisSourceFactory.java
chunjun-connectors/chunjun-connector-redis/src/main/java/com/dtstack/chunjun/connector/redis/table/RedisDynamicTableFactory.java
chunjun-connectors/chunjun-connector-redis/src/main/java/com/dtstack/chunjun/connector/redis/util/RedisUtil.java
chunjun-examples/json/redis/redis_source.json
chunjun-examples/sql/redis/redis_stream.sql
docs_zh/ChunJun连接器/redis/redis_source.md

Add source connector and reader connector of redis.

[feat-#1062][redis] Add source connector and reader connector of redis.

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/sink/DynamicPreparedStmt.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/sink/JdbcOutputFormat.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/sink/PreparedStmtProxy.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/statement/FieldNamedPreparedStatement.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/statement/FieldNamedPreparedStatementImpl.java

check dbConn valid before write record,if semantic is ExactlyOnce job will be set to fail when dbConn is invalid
Fixes #1103 .

[hotfix-#1103][jdbc] check dbConn valid before write record

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/converter/JdbcColumnConverter.java
chunjun-core/src/main/java/com/dtstack/chunjun/converter/AbstractRowConverter.java

[hotfix-1097] 修复数据库字段为null时，同步空指针问题

---

docs_zh/快速开始.md

add content about k8s quickstart
（https://github.com/DTStack/chunjun/issues/1089）

Quickstart add k8s content

---

chunjun-assembly/src/main/assembly/assembly.xml

…un-dist directory 2.remove doc and jars content
1.Move the chunjun-dist content to the chunjun-dist directory 
2.remove doc and jars content
#1172

[hotfix-#1172][assembly] Rebuild the chunjun-dist.tar.gz file structure

---

chunjun-connectors/chunjun-connector-cassandra/src/main/java/com/dtstack/chunjun/connector/cassandra/source/CassandraDynamicTableSource.java
chunjun-connectors/chunjun-connector-hbase-base/src/main/java/com/dtstack/chunjun/connector/hbase/table/BaseHBaseDynamicTableSource.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcDynamicTableSource.java
chunjun-connectors/chunjun-connector-kudu/src/main/java/com/dtstack/chunjun/connector/kudu/table/KuduDynamicTableSource.java
chunjun-connectors/chunjun-connector-redis/src/main/java/com/dtstack/chunjun/connector/redis/source/RedisDynamicTableSource.java

When lookup-type is 'NONE', each data will trigger the logic of querying data.
Fixes # (1179).

[hotfix-#1179][lookup] ChunJun 1.12 dimension table cannot be associated with the latest data

---

chunjun-assembly/pom.xml
chunjun-assembly/src/main/assembly/assembly.xml

modify chunjun-assembly's pom.xml and assembly to rename package install filename the issue address is [#1183 ]
{https://github.com/DTStack/chunjun/issues/1183}

[feat-#1183][assembly] rename install filename

---

chunjun-connectors/chunjun-connector-oraclelogminer/src/main/java/com/dtstack/chunjun/connector/oraclelogminer/listener/LogParser.java
chunjun-core/src/test/java/com/dtstack/chunjun/util/UnicodeToStringTest.java

[feat-#1193]oracle support nchar、nvarchar2 chinese value

[feat-#1193]oracle support nchar、nvarchar2 chinese value

---

docs_zh/ChunJun连接器/hbase/hbase-sink.md

modify hbase doc about support type
Fixes #1200

[doc-#1200] modify hbase doc about support type

---

chunjun-core/src/main/java/com/dtstack/chunjun/util/JobUtil.java

[hotfix-#1202] JobUtil submit job with ${a} dynamic parameters error.

---

chunjun-e2e/README_CH.md

[feat-#1206][e2e] Add E2e Readme.md.

---

chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/options/DorisConf.java

Fixes # ([issue 1171](https://github.com/DTStack/chunjun/issues/1171)).

fix bug that lack param of batchSize for Doris Sink config 

---

chunjun-connectors/chunjun-connector-sqlservercdc/src/main/java/com/dtstack/chunjun/connector/sqlservercdc/inputFormat/SqlServerCdcInputFormatBuilder.java

Fix the npe using sqlserver cdc connector in standalone mode.
Fixes # (#1212).

[hotfix-#1212][sqlserver cdc] Fix the npe using sqlserver cdc connector in standalone mode.

---

chunjun-e2e/src/test/resources/docker/flink/standalone/Dockerfile

[feat-e2e]#1220 flink download link is invalid on dockerfile

---

docs_zh/ChunJun 通用配置详解.md

fix pluginName of Mysql in MetricPluginConf.

[docs] fix pluginName of Mysql in MetricPluginConf.

---

docs_zh/快速开始.md

update Hyperlink of video about submitting job in Yarn Per-Job mode.

[docs] update Hyperlink of video about submitting job in Yarn Per-Job mode

---

chunjun-connectors/chunjun-connector-jdbc-base/src/test/java/com/dtstack/chunjun/connector/jdbc/converter/JdbcColumnConverterTest.java
chunjun-connectors/chunjun-connector-jdbc-base/src/test/java/com/dtstack/chunjun/connector/jdbc/converter/JdbcRawTypeConverterTest.java
chunjun-connectors/chunjun-connector-jdbc-base/src/test/java/com/dtstack/chunjun/connector/jdbc/converter/JdbcRowConverterTest.java
chunjun-connectors/chunjun-connector-jdbc-base/src/test/java/com/dtstack/chunjun/connector/jdbc/dialect/JdbcDialectTest.java
chunjun-connectors/chunjun-connector-jdbc-base/src/test/java/com/dtstack/chunjun/connector/jdbc/sink/JdbcOutputFormatTest.java
chunjun-connectors/chunjun-connector-jdbc-base/src/test/java/com/dtstack/chunjun/connector/jdbc/sink/SinkFactoryTest.java
chunjun-connectors/chunjun-connector-jdbc-base/src/test/java/com/dtstack/chunjun/connector/jdbc/source/JdbcInputFormatBuilderTest.java
chunjun-connectors/chunjun-connector-jdbc-base/src/test/java/com/dtstack/chunjun/connector/jdbc/source/JdbcInputFormatTest.java
chunjun-connectors/chunjun-connector-jdbc-base/src/test/java/com/dtstack/chunjun/connector/jdbc/source/SourceFactoryTest.java
chunjun-connectors/chunjun-connector-jdbc-base/src/test/java/com/dtstack/chunjun/connector/jdbc/source/distribute/DistributeJdbcInputFormatTest.java
chunjun-connectors/chunjun-connector-jdbc-base/src/test/java/com/dtstack/chunjun/connector/jdbc/source/distribute/SourceFactoryTest.java
chunjun-connectors/chunjun-connector-jdbc-base/src/test/java/com/dtstack/chunjun/connector/jdbc/table/JdbcDynamicTableFactoryTest.java
chunjun-connectors/chunjun-connector-jdbc-base/src/test/java/com/dtstack/chunjun/connector/jdbc/util/JdbcUtilTest.java
chunjun-connectors/chunjun-connector-jdbc-base/src/test/resources/distribute_sync_test.json
chunjun-connectors/chunjun-connector-jdbc-base/src/test/resources/sync_test.json

[feat][test]add jdbc-base unit test

---

chunjun-connectors/chunjun-connector-rabbitmq/pom.xml
chunjun-connectors/chunjun-connector-rabbitmq/src/main/java/com/dtstack/chunjun/connector/rabbitmq/options/RabbitmqOptions.java
chunjun-connectors/chunjun-connector-rabbitmq/src/main/java/com/dtstack/chunjun/connector/rabbitmq/source/RabbitmqDynamicTableSource.java
chunjun-connectors/chunjun-connector-rabbitmq/src/main/java/com/dtstack/chunjun/connector/rabbitmq/table/RabbitmqDynamicTableFactory.java
chunjun-connectors/chunjun-connector-rabbitmq/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
chunjun-connectors/pom.xml
chunjun-examples/sql/rabbitmq/rabbitmq_stream.sql
chunjun-local-test/pom.xml
docs_zh/ChunJun连接器/rabbitmq/rabbitmq-source.md

add rabbitmq sql source plugin #1246

[feat-#1246][rabbitmq] add rabbitmq sql source plugin

---

chunjun-connectors/chunjun-connector-db2/src/main/java/com/dtstack/chunjun/connector/db2/converter/Db2ColumnConverter.java

db2 does not support clob type #1253

[hotfix-#1253][db2] db2 support clob type

---

README.md

Signed-off-by: FlechazoW <35768015+FlechazoW@users.noreply.github.com>

[README] Remove expired content.

---

chunjun-connectors/chunjun-connector-kafka/pom.xml
chunjun-connectors/chunjun-connector-kafka/src/test/java/com/dtstack/chunjun/connector/kafka/adapter/StartupModeAdapterTest.java
chunjun-connectors/chunjun-connector-kafka/src/test/java/com/dtstack/chunjun/connector/kafka/conf/KafkaConfTest.java
chunjun-connectors/chunjun-connector-kafka/src/test/java/com/dtstack/chunjun/connector/kafka/converter/ConverterTest.java
chunjun-connectors/chunjun-connector-kafka/src/test/java/com/dtstack/chunjun/connector/kafka/deserializer/DtKafkaDeserializerTest.java
chunjun-connectors/chunjun-connector-kafka/src/test/java/com/dtstack/chunjun/connector/kafka/partitioner/CustomerFlinkPartitionTest.java
chunjun-connectors/chunjun-connector-kafka/src/test/java/com/dtstack/chunjun/connector/kafka/sink/KafkaSinkFactoryTest.java
chunjun-connectors/chunjun-connector-kafka/src/test/java/com/dtstack/chunjun/connector/kafka/source/KafkaSourceFactoryTest.java
chunjun-core/src/main/java/com/dtstack/chunjun/dirty/consumer/DefaultDirtyDataCollector.java
chunjun-core/src/main/java/com/dtstack/chunjun/dirty/utils/DirtyConfUtil.java
chunjun-core/src/main/java/com/dtstack/chunjun/dirty/utils/TablePrintUtil.java
chunjun-core/src/main/java/com/dtstack/chunjun/util/DataSyncFactoryUtil.java
chunjun-core/src/main/java/com/dtstack/chunjun/util/DateUtil.java

[hotfix]oracle type modify on sql & adjust to get unique key method

---

chunjun-core/src/main/java/com/dtstack/chunjun/Main.java

Sync job disable operator chains to improve performance

[hotfix][main]Sync jobs disable operator chains

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/sink/JdbcOutputFormat.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/util/JdbcUtil.java
chunjun-connectors/chunjun-connector-oracle/src/main/java/com/dtstack/chunjun/connector/oracle/converter/OracleRowConverter.java
chunjun-connectors/chunjun-connector-oraclelogminer/src/main/java/com/dtstack/chunjun/connector/oraclelogminer/converter/OracleRawTypeConverter.java
chunjun-core/src/main/java/com/dtstack/chunjun/Main.java
chunjun-core/src/main/java/com/dtstack/chunjun/element/column/TimestampColumn.java

[Release] Release v1.12.6

---

chunjun-connectors/chunjun-connector-hdfs/pom.xml
chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/InputSplit/HdfsOrcInputSplit.java

Hdfs connector support orc fileType
#565

[hotfix-#565][chunjun-hdfs-connector] hadoop3.x version support orc

---

chunjun-connectors/chunjun-connector-kudu/src/main/java/com/dtstack/chunjun/connector/kudu/converter/KuduRowConverter.java

[hotfix] kudu:GenericRowData can not cast ColumnRowData

---

flinkx-connectors/flinkx-connector-oceanbase/pom.xml

升级oceanbase版本

---

chunjun-connectors/chunjun-connector-binlog/pom.xml
chunjun-core/pom.xml
pom.xml

Fix the missing dependency, and rename.

[Hotfix][POM] Fix the missing dependency, and rename.

---

chunjun-connectors/chunjun-connector-dm/src/main/java/com/dtstack/chunjun/connector/dm/converter/DmColumnConverter.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/converter/JdbcColumnConverter.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcSourceFactory.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/util/JdbcUtil.java

… use "*" in columnInfo
1.get metadata from resultSetMetaData 2.support customSql use "*" in columnInfo
#1284

[feat-#1284][jdbc]get metadata from resultSetMetaData 

---

chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/converter/HdfsOrcColumnConverter.java
chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/converter/HdfsParquetColumnConverter.java
chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/converter/HdfsTextColumnConverter.java
chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/sink/HdfsSinkFactory.java
chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/source/HdfsSourceFactory.java
chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/util/HdfsUtil.java
chunjun-connectors/chunjun-connector-hive/src/main/java/com/dtstack/chunjun/connector/hive/sink/HiveOutputFormat.java
chunjun-core/src/main/java/com/dtstack/chunjun/converter/AbstractRowConverter.java

add assembleFieldProps for hdfs-connector
#1293

[feat-#1293][chunjun-connector-hdfs] add assembleFieldProps for hdfs-connector

---

bin/submit.sh

display Reference site while submitting job like following:
```
#
#
####
Reference site: https://dtstack.github.io/chunjun
ChunJun starting ...
```

[bin] display Reference site while submitting job.

---

README.md

Signed-off-by: FlechazoW <35768015+FlechazoW@users.noreply.github.com>
Update the description of 'ChunJun'.

[Improve][README.md] Update the description of 'ChunJun'.

---

.gitignore
chunjun-assembly/pom.xml
chunjun-assembly/src/main/assembly/assembly.xml

Adjust the output and package of assembly.

[Improve][Assembly] Adjust the output and package of assembly.

---

chunjun-e2e/src/test/java/com/dtstack/chunjun/connector/containers/ftp/SftpContainer.java
pom.xml

[Improve][Licenses] Add Apache 2.0 license.

---

chunjun-ddl/chunjun-ddl-base/pom.xml
chunjun-ddl/chunjun-ddl-mysql/pom.xml
chunjun-ddl/chunjun-ddl-oracle/pom.xml

Change the scope of 'ddl-base' to 'compile' and change the package of 'ddl-base' to 'pom'.
None.

[Improve][DDL][POM] Change the pom of 'ddl-base'

---

chunjun-ddl/chunjun-ddl-base/pom.xml
chunjun-ddl/chunjun-ddl-mysql/pom.xml
chunjun-ddl/chunjun-ddl-oracle/pom.xml

Fix the error that 'mvn package' failed.
None.

[HOTFIX][DDL-Base] Fix the error that 'mvn package' failed.

---

chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/converter/DorisColumnConverter.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/converter/DorisHttpRowConverter.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/converter/DorisRowTypeConverter.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/options/DorisConf.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/options/DorisConfBuilder.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/options/DorisKeys.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/options/DorisOptions.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/options/LoadConf.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/options/LoadConfBuilder.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/rest/Carrier.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/rest/DorisLoadClient.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/rest/DorisStreamLoad.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/rest/FeRestService.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/rest/module/Backend.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/rest/module/BackendRow.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/rest/module/Field.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/rest/module/PartitionDefinition.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/rest/module/QueryPlan.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/rest/module/RespContent.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/rest/module/Schema.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/rest/module/Tablet.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/sink/DorisDynamicTableSink.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/sink/DorisHttpOutputFormat.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/sink/DorisHttpOutputFormatBuilder.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/sink/DorisSinkFactory.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/source/DorisSourceFactory.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/table/DorisDynamicTableFactory.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/conf/JdbcConf.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/util/JdbcUtil.java

[Improve][Connector][Doris] Improve doris source.

---

README.md

As title.
Signed-off-by: Wey Gu <weyl.gu@gmail.com>

chore: typo fix of readme

---

docs_zh/ChunJun连接器/ftp/ftp-source.md

Update ftp docs, add ```maxFetchSize``` config
Fixes #1379

[feat-#1379][ftp][docs]add maxFetchSize

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/util/JdbcUtil.java

[hotfix][jdbc-connector] pgsql query metadata exception

---

chunjun-core/src/main/java/com/dtstack/chunjun/Main.java
chunjun-core/src/main/java/com/dtstack/chunjun/options/Options.java
chunjun-core/src/main/java/com/dtstack/chunjun/util/JobUtil.java

add parameters in json format
Fixes #1392

[Feat-#1392][core] add parameters in json format

---

chunjun-clients/pom.xml
chunjun-clients/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
chunjun-connectors/chunjun-connector-stream/src/main/java/com/dtstack/chunjun/connector/stream/converter/StreamRowConverter.java
chunjun-connectors/pom.xml
chunjun-core/pom.xml
chunjun-core/src/main/java/com/dtstack/chunjun/util/TableUtil.java

[Improve][Client] Support Yarn perjob submit.
Fixes None.

[Improve][Client] Support Yarn perjob submit.

---

chunjun-clients/src/main/java/com/dtstack/chunjun/client/ClusterClientHelper.java
chunjun-clients/src/main/java/com/dtstack/chunjun/client/JobDeployer.java
chunjun-clients/src/main/java/com/dtstack/chunjun/client/Launcher.java
chunjun-clients/src/main/java/com/dtstack/chunjun/client/exception/DeploymentException.java
chunjun-clients/src/main/java/com/dtstack/chunjun/client/kubernetes/KubernetesApplicationClusterClientHelper.java
chunjun-clients/src/main/java/com/dtstack/chunjun/client/kubernetes/KubernetesSessionClusterClientHelper.java
chunjun-clients/src/main/java/com/dtstack/chunjun/client/standalone/StandaloneClusterClientHelper.java
chunjun-clients/src/main/java/com/dtstack/chunjun/client/yarn/YarnConfLoader.java
chunjun-clients/src/main/java/com/dtstack/chunjun/client/yarn/YarnPerJobClusterClientHelper.java
chunjun-clients/src/main/java/com/dtstack/chunjun/client/yarn/YarnSessionClusterClientHelper.java

Improve code struct.
Fixes  None.

[Improve][Client] Improve code struct.

---

chunjun-connectors/chunjun-connector-hbase-base/src/main/java/com/dtstack/chunjun/connector/hbase/converter/HBaseColumnConverter.java

[bugfix][hbase]fix hbase date type cast int error

---

chunjun-core/src/main/java/com/dtstack/chunjun/environment/MyLocalStreamEnvironment.java

delete tmp flink-distribute-cache-xxx dir
Fixes #1426

[environment-##1426] delete tmp flink-distribute-cache-xxx dir

---

chunjun-clients/src/main/java/com/dtstack/chunjun/client/yarn/YarnSessionClusterClientHelper.java

Chunjun client support submit task to hadoop with kerberos
Chunjun client support submit task to hadoop with kerberos
#1434

[bugfix][Client] Chunjun client support submit task to hadoop with kerberos

---

chunjun-connectors/chunjun-connector-mongodb/src/main/java/com/dtstack/chunjun/connector/mongodb/converter/MongodbColumnConverter.java

[hotfix-#1512][mongodb] Fix the bug that mongodb supports constants

---

flinkx-postgresql/flinkx-postgresql-core/src/main/java/com/dtstack/flinkx/postgresql/PostgresqlTypeConverter.java

This pr fixes the incorrect bytea date type conversion of postgresql.

hotfix[postgresql]: Fix incorrect bytea data type conversion.

---

chunjun-connectors/chunjun-connector-mongodb/src/main/java/com/dtstack/chunjun/connector/mongodb/converter/MongodbColumnConverter.java

[hotfix-#1518][mongodb] fix mongodb read data not support objectId type

---

chunjun-core/src/main/java/com/dtstack/chunjun/sql/parser/SetStmtParser.java
chunjun-core/src/main/java/com/dtstack/chunjun/sql/parser/SqlParser.java

[feat-#1525][core] sql mode supports set syntax

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcInputFormat.java
chunjun-core/src/main/java/com/dtstack/chunjun/metrics/BigIntegerAccumulator.java

… the amount of readable data was 0
Fixed the same issue for 1.12_release
#1553

[hotfix-#1553][jdbc] Fixed endlocation not being set  bug for 1.12_release

---

chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/sink/FtpOutputFormat.java
chunjun-local-test/src/main/java/com/dtstack/chunjun/local/test/LocalTest.java

Data missing when synchronizing data from source to ftp
Fixes #1567 .

[hotfix-#1567][ftp] Fix data missing when synchronizing data from source to ftp

---

chunjun-connectors/chunjun-connector-sybase/src/main/java/com/dtstack/chunjun/connector/sybase/converter/SybaseRawTypeConverter.java

sybase support double precision type
Fixes https://github.com/DTStack/chunjun/issues/1575.

[hotfix-1575][sybase] sybase support double precision type

---

chunjun-connectors/chunjun-connector-sybase/src/main/java/com/dtstack/chunjun/connector/sybase/converter/SybaseRawTypeConverter.java

[hotfix-#1579][sybase] fix sybase not support sysname type

---

chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/converter/DorisHttpRowConverter.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/rest/DorisLoadClient.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/rest/DorisStreamLoad.java

修复写入doris时数据中包含逗号导致写入多条记录问题。
Fixes #1589

[hotfix-#1589][doris]Fixed When the written data contains commas, a single record will become multiple records

---

chunjun-connectors/chunjun-connector-clickhouse/src/main/java/com/dtstack/chunjun/connector/clickhouse/sink/ClickhouseOutputFormat.java

[hotfix-#1564][clickhouse] fix clickhouse not support transaction.

---

chunjun-core/src/main/java/com/dtstack/chunjun/Main.java

解决用flink run 原生方式提交时报错 sql Parse Exception
Fixes #1591

[hotfix-#1591][core] Fixed Error ChunJunSqlParseException is reported when flink run natively submits

---

chunjun-connectors/chunjun-connector-db2/src/main/java/com/dtstack/chunjun/connector/db2/dialect/Db2Dialect.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/sink/DorisSinkFactory.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/config/TableIdentify.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/dialect/JdbcDialect.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/sink/DynamicPreparedStmt.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/sink/JdbcOutputFormat.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/sink/JdbcSinkFactory.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcSourceFactory.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/util/JdbcUtil.java
chunjun-connectors/chunjun-connector-jdbc-base/src/test/java/com/dtstack/chunjun/connector/jdbc/sink/SinkFactoryTest.java
chunjun-connectors/chunjun-connector-jdbc-base/src/test/java/com/dtstack/chunjun/connector/jdbc/source/SourceFactoryTest.java
chunjun-connectors/chunjun-connector-jdbc-base/src/test/resources/sync_test.json
chunjun-connectors/chunjun-connector-mysql/src/main/java/com/dtstack/chunjun/connector/mysql/dialect/MysqlDialect.java
chunjun-connectors/chunjun-connector-oracle/src/main/java/com/dtstack/chunjun/connector/oracle/dialect/OracleDialect.java
chunjun-connectors/chunjun-connector-oraclelogminer/src/main/java/com/dtstack/chunjun/connector/oraclelogminer/converter/LogMinerColumnConverter.java
chunjun-connectors/chunjun-connector-vertica11/src/main/java/com/dtstack/chunjun/connector/vertica11/sink/Vertica11OutputFormat.java

…rmation
1.Resolve an error in obtaining metadata from the database if schemaName or TableName contains special characters
2.Reduce unnecessary column fetching (fetching only those configured in the script)

[feat-#1594][jdbc]Optimize the acquisition of metadata information

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/converter/JdbcSyncConverter.java
chunjun-connectors/chunjun-connector-oceanbase/src/main/java/com/dtstack/chunjun/connector/oceanbase/converter/OceanbaseSyncConverter.java
chunjun-connectors/chunjun-connector-oceanbase/src/main/java/com/dtstack/chunjun/connector/oceanbase/dialect/OceanbaseDialect.java
chunjun-local-test/pom.xml
chunjun-local-test/src/main/java/com/dtstack/chunjun/local/test/LocalTest.java

[Hotfix][Oceanbase] Fix oceanbase can not read data.

---

.gitignore
.idea/vcs.xml

Add IssueNavigationLink for IDEA
before
after
None.

[Improve] Add IssueNavigationLink for IDEA

---

chunjun-core/src/main/java/com/dtstack/chunjun/Main.java

解决 local模式时不输出统计指标信息
Fixes #1601

[hotfix-#1601][core] Fixed Statistical indicator information is not utput in local mode

---

.github/labeler.yml
.github/workflows/label.yml

Add an action to auto label pr based on the files it changed. 
example:

[github] Add labeler for pull-request

---

chunjun-connectors/chunjun-connector-mysql/pom.xml

解决mysql connector 运行找不到相关依赖问题，并升级mysql 驱动包版本
Fixes #1627

[hotfix-#1627][mysql] fixed dependency problem , Upgrade mysql connector dependencies

---

chunjun-clients/src/main/java/com/dtstack/chunjun/client/Launcher.java

fix NullPointerException in Launcher
Fixes # (1629).

[hotfix-#1629][client]fixed NullPointerException in local mode.

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/converter/JdbcSqlConverter.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/sink/JdbcOutputFormat.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcInputFormat.java
chunjun-connectors/chunjun-connector-mysql/src/main/java/com/dtstack/chunjun/connector/mysql/converter/MysqlRawTypeConverter.java

[feat-#1632][jdbc]Solve ClassCastException, optimize the problem of invalid database connection when writing
优化ClassCastException， 优化写入时数据库连接无效问题
Fixes #1632

[feat-#1632][jdbc]Solve ClassCastException, optimize the problem of invalid database connection when writing

---

chunjun-clients/pom.xml
chunjun-clients/src/main/java/com/dtstack/chunjun/client/Launcher.java
chunjun-core/src/main/java/com/dtstack/chunjun/Main.java

[hotfix-#1652][core]Fix problems in various operating modes

---

chunjun-connectors/chunjun-connector-hive/pom.xml
chunjun-connectors/chunjun-connector-hive/src/main/java/com/dtstack/chunjun/connector/hive/converter/HiveJdbcColumnConverter.java
chunjun-connectors/chunjun-connector-hive/src/main/java/com/dtstack/chunjun/connector/hive/converter/HiveRawTypeConverter.java
chunjun-connectors/chunjun-connector-hive/src/main/java/com/dtstack/chunjun/connector/hive/dialect/HiveDialect.java
chunjun-connectors/chunjun-connector-hive/src/main/java/com/dtstack/chunjun/connector/hive/source/HiveInputFormat.java
chunjun-connectors/chunjun-connector-hive/src/main/java/com/dtstack/chunjun/connector/hive/source/HiveSourceFactory.java
chunjun-connectors/chunjun-connector-hive/src/main/java/com/dtstack/chunjun/connector/hive/table/HiveDynamicTableFactory.java

[feat-#1649][hive] Support jdbc mode to read hive

---

chunjun-connectors/chunjun-connector-kingbase/pom.xml
chunjun-connectors/chunjun-connector-kingbase/src/main/java/com/dtstack/chunjun/connector/kingbase/converter/KingbaseRawTypeMapper.java
chunjun-connectors/chunjun-connector-kingbase/src/main/java/com/dtstack/chunjun/connector/kingbase/converter/KingbaseSqlConverter.java
chunjun-connectors/chunjun-connector-kingbase/src/main/java/com/dtstack/chunjun/connector/kingbase/converter/KingbaseSyncConverter.java
chunjun-connectors/chunjun-connector-kingbase/src/main/java/com/dtstack/chunjun/connector/kingbase/dialect/KingbaseDialect.java
chunjun-connectors/chunjun-connector-kingbase/src/main/java/com/dtstack/chunjun/connector/kingbase/sink/KingbaseSinkFactory.java
chunjun-connectors/chunjun-connector-kingbase/src/main/java/com/dtstack/chunjun/connector/kingbase/source/KingbaseSourceFactory.java
chunjun-connectors/chunjun-connector-kingbase/src/main/java/com/dtstack/chunjun/connector/kingbase/table/KingbaseDynamicTableFactory.java
chunjun-connectors/chunjun-connector-kingbase/src/main/java/com/dtstack/chunjun/connector/kingbase/util/KingbaseConstants.java
chunjun-connectors/chunjun-connector-kingbase/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
chunjun-connectors/pom.xml
chunjun-core/src/main/java/com/dtstack/chunjun/converter/AbstractRowConverter.java
chunjun-local-test/pom.xml

[Feature][Connector][Kingbase] Add kingbase connector.

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcDynamicTableSource.java
chunjun-connectors/chunjun-connector-kingbase/src/main/java/com/dtstack/chunjun/connector/kingbase/dialect/KingbaseDialect.java

解决 jdbc 在flink 1.16g下词下推变更
Fixes #1662

[bug-#1662][connector][jdbc] implementation provided for SupportsProjectionPushDown

---

chunjun-core/src/main/java/com/dtstack/chunjun/converter/AbstractRowConverter.java
chunjun-core/src/main/java/com/dtstack/chunjun/dirty/consumer/DirtyDataCollector.java
chunjun-core/src/test/java/com/dtstack/chunjun/dirty/consumer/DirtyDataCollectorTest.java

yarn-per-job模式，当有脏数据报错时可以输出脏数据详细信息
Fixes #1670

[feat-#1670][core] Support yarn log output dirty data details

---

chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/source/BaseHdfsInputFormat.java
chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/source/HdfsTextInputFormat.java

[hotfix-#1674][connector][hdfs] fixed Unexpected end of input stream

---

chunjun-connectors/chunjun-connector-hive/src/main/java/com/dtstack/chunjun/connector/hive/source/HiveInputFormat.java
chunjun-connectors/chunjun-connector-hive/src/main/java/com/dtstack/chunjun/connector/hive/table/HiveDynamicTableFactory.java
chunjun-connectors/chunjun-connector-hive/src/main/java/com/dtstack/chunjun/connector/hive/util/HiveDbUtil.java

[hotfix-#1682][connector][hive] fixed hive jdbc read timed out

---

chunjun-connectors/chunjun-connector-hbase-base/src/test/java/com/dtstack/chunjun/connector/hbase/config/HBaseConfigTest.java
chunjun-connectors/chunjun-connector-hbase-base/src/test/java/com/dtstack/chunjun/connector/hbase/sink/HBaseOutputFormatTest.java
chunjun-connectors/chunjun-connector-hbase-base/src/test/java/com/dtstack/chunjun/connector/hbase/source/HBaseInputFormatTest.java
chunjun-connectors/chunjun-connector-hbase-base/src/test/java/com/dtstack/chunjun/connector/hbase/util/ScanBuilderTest.java
chunjun-core/src/main/java/com/dtstack/chunjun/typeutil/serializer/base/TimeColumnSerializer.java
chunjun-core/src/test/java/com/dtstack/chunjun/typeutil/serializer/base/BooleanColumnSerializerTest.java
chunjun-core/src/test/java/com/dtstack/chunjun/typeutil/serializer/base/ByteColumnSerializerTest.java
chunjun-core/src/test/java/com/dtstack/chunjun/typeutil/serializer/base/BytesColumnSerializerTest.java
chunjun-core/src/test/java/com/dtstack/chunjun/typeutil/serializer/base/DecimalColumnSerializerTest.java
chunjun-core/src/test/java/com/dtstack/chunjun/typeutil/serializer/base/DoubleColumnSerializerTest.java
chunjun-core/src/test/java/com/dtstack/chunjun/typeutil/serializer/base/FloatColumnSerializerTest.java
chunjun-core/src/test/java/com/dtstack/chunjun/typeutil/serializer/base/IntColumnSerializerTest.java
chunjun-core/src/test/java/com/dtstack/chunjun/typeutil/serializer/base/LongColumnSerializerTest.java
chunjun-core/src/test/java/com/dtstack/chunjun/typeutil/serializer/base/MapColumnSerializerTest.java
chunjun-core/src/test/java/com/dtstack/chunjun/typeutil/serializer/base/ShortColumnSerializerTest.java
chunjun-core/src/test/java/com/dtstack/chunjun/typeutil/serializer/base/SqlDateColumnSerializerTest.java
chunjun-core/src/test/java/com/dtstack/chunjun/typeutil/serializer/base/StringColumnSerializerTest.java
chunjun-core/src/test/java/com/dtstack/chunjun/typeutil/serializer/base/TimeColumnSerializerTest.java
chunjun-core/src/test/java/com/dtstack/chunjun/typeutil/serializer/base/TimestampColumnSerializerTest.java

Fix test problems caused by type enhancement

[hotfix][test]Fix test problems caused by type enhancement

---

chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/options/FtpOptions.java
chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/table/FtpDynamicTableFactory.java

[hotfix-#1697][connector][ftp] fixed unsupported options

---

chunjun-core/src/main/java/com/dtstack/chunjun/config/FieldConfig.java

Fix json script deserialization error
#1704

[hotfix-#1704][core] Fix json script deserialization error

---

chunjun-connectors/chunjun-connector-binlog/pom.xml
chunjun-core/pom.xml
chunjun-local-test/pom.xml

[hotfix-#1711][Binlog] Adapt to binlog plugin

---

chunjun-connectors/chunjun-connector-gbase/pom.xml
chunjun-connectors/chunjun-connector-gbase/src/main/java/com/dtstack/chunjun/connector/gbase/converter/GbaseRawTypeConverter.java
chunjun-connectors/chunjun-connector-gbase/src/main/java/com/dtstack/chunjun/connector/gbase/dialect/GbaseDialect.java
chunjun-connectors/chunjun-connector-gbase/src/main/java/com/dtstack/chunjun/connector/gbase/sink/GbaseSinkFactory.java
chunjun-connectors/chunjun-connector-gbase/src/main/java/com/dtstack/chunjun/connector/gbase/source/GbaseSourceFactory.java
chunjun-connectors/chunjun-connector-gbase/src/main/java/com/dtstack/chunjun/connector/gbase/table/GbaseDynamicTableFactory.java
chunjun-connectors/chunjun-connector-gbase/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
chunjun-connectors/pom.xml

[hotfix-#1672][connector][gbase] add gbase connector

---

chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/sink/BaseHdfsOutputFormat.java

[hotfix-#1724] [connector][hdfs]fix BaseHdfsOutputFormat CannotObtainBlockLengthException , Improve task stability
the issue address is https://github.com/DTStack/chunjun/issues/1724

[hotfix-#1724] [connector][hdfs]fix CannotObtainBlockLengthException

---

chunjun-connectors/chunjun-connector-dm/pom.xml
chunjun-connectors/chunjun-connector-elasticsearch7/pom.xml

[hotfix-#1710][connector][dm][elasticsearch7] fixed not found dependent package

---

chunjun-connectors/chunjun-connector-starrocks/pom.xml
chunjun-connectors/chunjun-connector-starrocks/src/main/java/com/dtstack/chunjun/connector/starrocks/config/StarRocksConfig.java
chunjun-connectors/chunjun-connector-starrocks/src/main/java/com/dtstack/chunjun/connector/starrocks/options/StarRocksSinkOptions.java
chunjun-connectors/chunjun-connector-starrocks/src/main/java/com/dtstack/chunjun/connector/starrocks/sink/MappedWriteProcessor.java
chunjun-connectors/chunjun-connector-starrocks/src/main/java/com/dtstack/chunjun/connector/starrocks/sink/NormalWriteProcessor.java
chunjun-connectors/chunjun-connector-starrocks/src/main/java/com/dtstack/chunjun/connector/starrocks/sink/StarRocksDynamicTableSink.java
chunjun-connectors/chunjun-connector-starrocks/src/main/java/com/dtstack/chunjun/connector/starrocks/sink/StarRocksOutputFormatBuilder.java
chunjun-connectors/chunjun-connector-starrocks/src/main/java/com/dtstack/chunjun/connector/starrocks/streamload/StreamLoadManager.java
chunjun-connectors/chunjun-connector-starrocks/src/main/java/com/dtstack/chunjun/connector/starrocks/table/StarRocksDynamicTableFactory.java

Add table structure cache
Added configuration for isCacheTableStruct and checkStructFirstTime to reduce database interaction
#1748

[hotfix-#1748][starrocks] Add table structure cache

---

chunjun-connectors/chunjun-connector-oceanbasecdc/src/main/java/com/dtstack/chunjun/connector/oceanbasecdc/entity/OceanBaseCdcEventRow.java
chunjun-connectors/chunjun-connector-oceanbasecdc/src/main/java/com/dtstack/chunjun/connector/oceanbasecdc/listener/OceanBaseCdcListener.java
chunjun-examples/json/oceanbasecdc/oceanbasecdc_stream_transformer.json

[fix][connector][ocenabasecdc] fix value converter and buffer flush

---

chunjun-connectors/chunjun-connector-elasticsearch7/src/main/java/com/dtstack/chunjun/connector/elasticsearch7/source/ElasticsearchInputFormat.java

[hotfix-#1750][connector][elasticsearch7] fixed Unable to parse response body

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcInputFormat.java

[hotfix-#1741][connector][jdbc] throw query interrupted exception

---

chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/sink/DorisDynamicTableSink.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/table/DorisDynamicTableFactory.java

[Feature-#1781][connector] [doris] supports doris pre-sql and post-sql

---

chunjun-connectors/chunjun-connector-starrocks/src/main/java/com/dtstack/chunjun/connector/starrocks/config/StarRocksConfig.java
chunjun-connectors/chunjun-connector-starrocks/src/main/java/com/dtstack/chunjun/connector/starrocks/options/StreamLoadOptions.java
chunjun-connectors/chunjun-connector-starrocks/src/main/java/com/dtstack/chunjun/connector/starrocks/sink/StarRocksOutputFormat.java
chunjun-connectors/chunjun-connector-starrocks/src/main/java/com/dtstack/chunjun/connector/starrocks/streamload/StarRocksQueryVisitor.java
chunjun-connectors/chunjun-connector-starrocks/src/main/java/com/dtstack/chunjun/connector/starrocks/table/StarRocksDynamicTableFactory.java

[Feature-#1784][connector][starrocks] Support running pre-execution and post-execution sql

---

chunjun-connectors/chunjun-connector-mongodb/pom.xml

[hotfix-#1811][connector][mongodb] Fixed missing dependencies

---

chunjun-connectors/chunjun-connector-oracle/src/main/java/com/dtstack/chunjun/connector/oracle/converter/OracleSqlConverter.java

Fixes # (1814).
Consuming oracle data incorectly uses jdbc-base module's createInternalConverter logic

[hotfix-#1814][chunjun-connector-oracle] Consuming oracle data incorectly uses jdbc-base module's createInternalConverter logic

---

chunjun-connectors/chunjun-connector-oracle/src/main/java/com/dtstack/chunjun/connector/oracle/converter/OracleSqlConverter.java

[hotfix-#1823][connector][oracle] oracle Connector incorrectly consumed date-type data

---

pom.xml

[hotfix-#1829][chunjun] Fixed view checkpoints error report

---

chunjun-connectors/chunjun-connector-kafka/pom.xml

[hotfix-#1834][connector][kafka] Fixed missing dependencies

---

chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/table/HdfsDynamicTableFactory.java
chunjun-core/src/main/java/com/dtstack/chunjun/config/BaseFileConfig.java
chunjun-core/src/main/java/com/dtstack/chunjun/sink/format/BaseFileOutputFormat.java
chunjun-core/src/main/java/com/dtstack/chunjun/table/options/BaseFileOptions.java
chunjun-examples/sql/hdfs/stream_sink_hdfs.sql

[hotfix-#1745][connector][hdfs][hive] Data loss occurs when multiple tasks write to the same hdfs (or hive) data source

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/converter/JdbcSqlConverter.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/lookup/JdbcLruTableFunction.java
chunjun-core/src/main/java/com/dtstack/chunjun/lookup/AbstractLruTableFunction.java
chunjun-core/src/main/java/com/dtstack/chunjun/util/JsonUtil.java

[hotfix-#1849][jdbc] fixed load data using lru method is empty, hide clear text passwords in logs, fixed build cache key when GenericRowData

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/config/JdbcConfig.java

[bugfix][jdbc] fix uniqueKey NPE

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcDynamicTableSource.java

…s data by field name rather than index #1853

[hotfix-#1853] [connector jdbc] jdbc toInternal methods should process data by field name rather than index #1853

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/table/JdbcDynamicTableFactory.java

…returns an unmodifiable list, but modifications are made in the code

[hotfix-#1869] [connector-jdbc-base] Using Collections.singletonList returns an unmodifiable list, but modifications are made in the code

---

chunjun-connectors/chunjun-connector-jdbc-base/src/test/java/com/dtstack/chunjun/connector/jdbc/sink/SinkFactoryTest.java
chunjun-connectors/chunjun-connector-jdbc-base/src/test/java/com/dtstack/chunjun/connector/jdbc/source/JdbcInputFormatBuilderTest.java
chunjun-connectors/chunjun-connector-jdbc-base/src/test/java/com/dtstack/chunjun/connector/jdbc/source/JdbcInputFormatTest.java
chunjun-connectors/chunjun-connector-jdbc-base/src/test/java/com/dtstack/chunjun/connector/jdbc/source/SourceFactoryTest.java
chunjun-connectors/chunjun-connector-jdbc-base/src/test/java/com/dtstack/chunjun/connector/jdbc/source/distribute/DistributeJdbcInputFormatTest.java
chunjun-core/pom.xml
chunjun-core/src/main/java/com/dtstack/chunjun/Main.java
chunjun-core/src/main/java/com/dtstack/chunjun/environment/EnvFactory.java
chunjun-core/src/main/java/com/dtstack/chunjun/util/ConnectorNameConvertUtil.java
chunjun-core/src/main/java/com/dtstack/chunjun/util/PluginUtil.java
chunjun-core/src/main/java/org/apache/flink/table/factories/FactoryUtil.java
chunjun-core/src/test/java/com/dtstack/chunjun/config/BaseFileConfigTest.java

修复local 模式下connector 无法识别和运行异常

---

chunjun-connectors/chunjun-connector-ftp/pom.xml
chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/client/excel/ExcelReadListener.java
chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/converter/FtpSqlConverter.java
chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/handler/FtpHandler.java
chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/iformat/ExcelFileFormat.java
chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/source/FtpDynamicTableSource.java
chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/source/FtpInputFormat.java

[Feature-#1877][ftp] Supports reading Chinese paths and optimizing reading excel

---

chunjun-connectors/chunjun-connector-hbase-base/src/main/java/com/dtstack/chunjun/connector/hbase/HBaseTableSchema.java
chunjun-connectors/chunjun-connector-hbase-base/src/main/java/com/dtstack/chunjun/connector/hbase/config/HBaseConfig.java
chunjun-connectors/chunjun-connector-hbase-base/src/main/java/com/dtstack/chunjun/connector/hbase/config/HBaseConfigConstants.java
chunjun-connectors/chunjun-connector-hbase-base/src/main/java/com/dtstack/chunjun/connector/hbase/converter/HBaseFlatRowConverter.java
chunjun-connectors/chunjun-connector-hbase-base/src/main/java/com/dtstack/chunjun/connector/hbase/converter/HBaseSerde.java
chunjun-connectors/chunjun-connector-hbase-base/src/main/java/com/dtstack/chunjun/connector/hbase/converter/HBaseSqlConverter.java
chunjun-connectors/chunjun-connector-hbase-base/src/main/java/com/dtstack/chunjun/connector/hbase/source/HBaseInputFormat.java
chunjun-connectors/chunjun-connector-hbase-base/src/main/java/com/dtstack/chunjun/connector/hbase/source/HBaseInputFormatBuilder.java
chunjun-connectors/chunjun-connector-hbase-base/src/main/java/com/dtstack/chunjun/connector/hbase/source/HBaseSourceFactoryBase.java
chunjun-connectors/chunjun-connector-hbase-base/src/main/java/com/dtstack/chunjun/connector/hbase/table/HBaseDynamicTableFactoryBase.java
chunjun-connectors/chunjun-connector-hbase-base/src/main/java/com/dtstack/chunjun/connector/hbase/table/HBaseDynamicTableSink.java
chunjun-connectors/chunjun-connector-hbase-base/src/main/java/com/dtstack/chunjun/connector/hbase/table/HBaseDynamicTableSource.java
chunjun-connectors/chunjun-connector-hbase-base/src/main/java/com/dtstack/chunjun/connector/hbase/table/HBaseOptions.java
chunjun-connectors/chunjun-connector-hbase-base/src/main/java/com/dtstack/chunjun/connector/hbase/table/lookup/HBaseAllTableFunction.java
chunjun-connectors/chunjun-connector-hbase-base/src/main/java/com/dtstack/chunjun/connector/hbase/table/lookup/HBaseLruTableFunction.java
chunjun-connectors/chunjun-connector-hbase-base/src/main/java/com/dtstack/chunjun/connector/hbase/util/HBaseHelper.java
chunjun-connectors/chunjun-connector-hbase-base/src/test/java/com/dtstack/chunjun/connector/hbase/HBaseTableSchemaTest.java
chunjun-connectors/chunjun-connector-hbase-base/src/test/java/com/dtstack/chunjun/connector/hbase/converter/HBaseSerdeTest.java
chunjun-connectors/chunjun-connector-hbase2/pom.xml
chunjun-connectors/chunjun-connector-hbase2/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory

[Feature-#1886][hbase] New features in sql mode

---

chunjun-connectors/chunjun-connector-mysql/src/main/java/com/dtstack/chunjun/connector/mysql/converter/MysqlSqlConverter.java
chunjun-connectors/chunjun-connector-mysql/src/main/java/com/dtstack/chunjun/connector/mysql/dialect/MysqlDialect.java

[Feature-#1899][connector][mysql] The connector supports MySQL Driver 8.x

---

chunjun-connectors/chunjun-connector-ftp/pom.xml
chunjun-connectors/pom.xml

[Feature-#1897][gbasehk] annotation gbasehk connector

---

chunjun-connectors/chunjun-connector-hbase-base/src/test/java/com/dtstack/chunjun/connector/hbase/converter/HBaseSerdeTest.java

[hotfix-1906][hbase]#1906 resolve hbase unit test failed

---

chunjun-connectors/chunjun-connector-starrocks/src/main/java/com/dtstack/chunjun/connector/starrocks/sink/StarRocksSinkFactory.java

[hotfix-1908][chunjun-connector-starrocks]: starrocks data size check

---

chunjun-connectors/chunjun-connector-clickhouse/src/main/java/com/dtstack/chunjun/connector/clickhouse/converter/ClickhouseRawTypeConverter.java

[Improve-#1914][chunjun-connector-clickhouse] Added support for map<string, unit> and map<string, int> data types

---

chunjun-connectors/chunjun-connector-kingbase/src/main/java/com/dtstack/chunjun/connector/kingbase/dialect/KingbaseDialect.java

[Feature-#1920][kingbase] fixed syntax error at or near "t1"
