flinkx-launcher/src/main/java/com/dtstack/flinkx/launcher/ClusterClientFactory.java

我在开始执行on yarn的时候 没有启动 yarn session
最后才发现是没有启动yarn session

当客户端没有启动yarn session的时候会报空指针错误

---

flinkx-core/pom.xml
flinkx-launcher/src/main/java/com/dtstack/flinkx/launcher/ClusterClientFactory.java
flinkx-launcher/src/main/java/com/dtstack/flinkx/launcher/LauncherOptionParser.java
flinkx-launcher/src/main/java/com/dtstack/flinkx/launcher/LauncherOptions.java

1.以命令行参数的方式指定detached
2. 完善flinkx-core/pom.xml文件

V1.7.0 dev-以命令行参数的方式指定detached

---

flinkx-core/src/main/java/com/dtstack/flinkx/outputformat/BaseRichOutputFormat.java
flinkx-mongodb/flinkx-mongodb-reader/src/main/java/com/dtstack/flinkx/mongodb/reader/MongodbInputFormat.java
flinkx-mongodb/flinkx-mongodb-reader/src/main/java/com/dtstack/flinkx/mongodb/reader/MongodbInputFormatBuilder.java

异常现象：
在向mysql插入过程中，如果遇到SqlException异常。那么会放入脏数据处理。但是，SqlException没有打印出来，用户在日志中发现不了任何SqlException日志，无法及时排除问题。设计者应该是考虑到脏数据太大，导致日志文件过大，因此隐藏了错误日志。
但是，我认为默认还是应该把SqlException打印到日志文件中。
解决思路：
跟踪com.dtstack.flinkx.clickhouse.format.ClickhouseOutputFormat以及com.dtstack.flinkx.kudu.writer.KuduOutputFormat
这2个类在插入失败时都会把错误打印出来
LOG.error("Write data error, index = {}, row = {}, e = {}", index, row, ExceptionUtil.getErrorMessage(e));
因此，按照此方式进行打印错误日志

插入异常被吞掉BUG

---

flinkx-kb/flinkx-kb-core/src/main/java/com/dtstack/flinkx/kafkabase/entity/kafkaState.java

kafkaState equals方法实现如下
```
// 类的成员变量
private String topic;
private Integer partition;
private Long offset;
private Long timestamp;
@Override
public boolean equals(Object o) {
if (this == o) return true;
if (o == null || getClass() != o.getClass()) return false;
kafkaState that = (kafkaState) o;
return partition == that.partition &&
offset == that.offset &&
timestamp == that.timestamp &&
topic.equals(that.topic);
}
```
按照我的理解， offset, timestamp的值按道理都不会存在Long对象的Cache中，也就是相同值的Long对象地址也会不同。 那么这里使用==去判断两者，导致的结果可能永远为False。 这里我认为应该实现为equals， 不知道我的理解是否正确， 还请指教
[issue](https://github.com/DTStack/flinkx/issues/356)

[hotfix-356][flinkx-kafka] 修复kafkaState类 equals方法错误实现问题

---

flinkx-kafka11/flinkx-kafka11-reader/src/main/java/com/dtstack/flinkx/kafka11/client/Kafka11Client.java

[flinkx-378] [kafka11]修复Kafka11Client错误的log4j日志类名 #379

[flinkx-378] [kafka11]修复Kafka11Client错误的log4j日志类名

---

flinkx-kb/flinkx-kb-core/src/main/java/com/dtstack/flinkx/kafkabase/util/KafkaUtil.java

case语句后面添加break解决earliest-offset不生效问题 #394。
[如图：]

[flinkx-394][kb] 解决earliest-offset不生效问题

---

docs/quickstart.md

After unzip 1.10_release.zip, we got flinkx-1.10_release instead of 1.10_release.

[Docs] fix flinkx unzip folder name from 1.10_release to flinkx-1.10_release

---

flinkx-connectors/flinkx-connector-redis/src/main/java/com/dtstack/flinkx/connector/redis/converter/RedisColumnConverter.java

当写入sink的数据类型为string时，value为源数据的value值组成的数组根据分隔符去组成一个新的字符串，并且不能看到key和value的对应关系，拿到sink数据后，也不能根据反序列化获得对应的对象。修改后，存入的数据是根据key和value一一对应组成map并转成json格式的string，拿出sink数据后，能够根据反序列化获得对应的对象。

[fix][connectors redis]redis sink values保留字段类型方便反序列化

---

flinkx-connectors/flinkx-connector-jdbc-base/src/main/java/com/dtstack/flinkx/connector/jdbc/sink/JdbcOutputFormat.java

jdbc connection in exact_once mode forget commit transaction.

fix[#622] jdbc connection in exact_once mode forget commit transaction.

---

docs/quickstart.md

修改git clone地址

---

docs/connectors-en/redis/redis-sink.md
docs/connectors/redis/redis-sink.md
flinkx-connectors/flinkx-connector-redis/src/main/java/com/dtstack/flinkx/connector/redis/options/RedisOptions.java
flinkx-connectors/flinkx-connector-redis/src/main/java/com/dtstack/flinkx/connector/redis/table/RedisDynamicTableFactory.java
flinkx-examples/sql/redis/stream_redis.sql

https://github.com/DTStack/chunjun/issues/710

[hotfix-710][redis] Fix writing to redis in sql mode reports illegal argument exception

---

flinkx-connectors/flinkx-connector-binlog/src/main/java/com/dtstack/flinkx/connector/binlog/inputformat/BinlogInputFormatBuilder.java
flinkx-connectors/flinkx-connector-elasticsearch7/src/main/java/com/dtstack/flinkx/connector/elasticsearch7/source/ElasticsearchInputFormatBuilder.java
flinkx-connectors/flinkx-connector-emqx/src/main/java/com/dtstack/flinkx/connector/emqx/source/EmqxInputFormatBuilder.java
flinkx-connectors/flinkx-connector-file/src/main/java/com/dtstack/flinkx/connector/file/source/FileInputFormatBuilder.java
flinkx-connectors/flinkx-connector-ftp/src/main/java/com/dtstack/flinkx/connector/ftp/source/FtpInputFormatBuilder.java
flinkx-connectors/flinkx-connector-hbase-1.4/src/main/java/com/dtstack/flinkx/connector/hbase14/source/HBaseInputFormatBuilder.java
flinkx-connectors/flinkx-connector-hdfs/src/main/java/com/dtstack/flinkx/connector/hdfs/source/HdfsDynamicTableSource.java
flinkx-connectors/flinkx-connector-hdfs/src/main/java/com/dtstack/flinkx/connector/hdfs/source/HdfsInputFormatBuilder.java
flinkx-connectors/flinkx-connector-hdfs/src/main/java/com/dtstack/flinkx/connector/hdfs/source/HdfsSourceFactory.java
flinkx-connectors/flinkx-connector-http/src/main/java/com/dtstack/flinkx/connector/http/inputformat/HttpInputFormatBuilder.java
flinkx-connectors/flinkx-connector-influxdb/src/main/java/com/dtstack/flinkx/connector/influxdb/source/InfluxdbInputFormatBuilder.java
flinkx-connectors/flinkx-connector-jdbc-base/src/main/java/com/dtstack/flinkx/connector/jdbc/source/JdbcInputFormatBuilder.java
flinkx-connectors/flinkx-connector-kudu/src/main/java/com/dtstack/flinkx/connector/kudu/source/KuduInputFormatBuilder.java
flinkx-connectors/flinkx-connector-mongodb/src/main/java/com/dtstack/flinkx/connector/mongodb/source/MongodbInputFormatBuilder.java
flinkx-connectors/flinkx-connector-mongodb/src/main/java/com/dtstack/flinkx/connector/mongodb/source/MongodbSourceFactory.java
flinkx-connectors/flinkx-connector-oraclelogminer/src/main/java/com/dtstack/flinkx/connector/oraclelogminer/inputformat/OracleLogMinerInputFormatBuilder.java
flinkx-connectors/flinkx-connector-pgwal/src/main/java/com/dtstack/flinkx/connector/pgwal/inputformat/PGWalInputFormatBuilder.java
flinkx-connectors/flinkx-connector-socket/src/main/java/com/dtstack/flinkx/connector/socket/inputformat/SocketInputFormatBuilder.java
flinkx-connectors/flinkx-connector-solr/src/main/java/com/dtstack/flinkx/connector/solr/source/SolrInputFormatBuilder.java
flinkx-connectors/flinkx-connector-solr/src/main/java/com/dtstack/flinkx/connector/solr/source/SolrSourceFactory.java
flinkx-connectors/flinkx-connector-sqlservercdc/src/main/java/com/dtstack/flinkx/connector/sqlservercdc/inputFormat/SqlServerCdcInputFormatBuilder.java
flinkx-connectors/flinkx-connector-stream/src/main/java/com/dtstack/flinkx/connector/stream/source/StreamInputFormatBuilder.java
flinkx-core/src/main/java/com/dtstack/flinkx/source/format/BaseRichInputFormatBuilder.java

Deal the warn if Raw use of parameterized class in the class extend BaseRichInputFormatBuilder.
The issus: #733

Deal the warn if Raw use of parameterized class

---

docs/connectors/http/http-sink.md
docs/connectors/http/http-source.md

[docs][http] Add http docs.

---

flinkx-clients/src/main/java/com/dtstack/flinkx/client/Launcher.java

Fix https://github.com/DTStack/chunjun/issues/744

[hotfix-744][client] fix directory is not configured NPE

---

flinkx-core/src/main/java/com/dtstack/flinkx/Main.java
flinkx-core/src/main/java/com/dtstack/flinkx/throwable/JobConfigException.java

[hotfix-794][core] fix job Configuration item is missing NPE

---

chunjun-core/src/main/java/com/dtstack/chunjun/options/Options.java

Fix Bug of 'Use 'chunjunDistDir' replace 'flinkxDistDir', then task failed with ClassNotFoundException.'

[hotfix-#843][core] Fix Bug of ' ChunJun can not find class of connector. '

---

chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/options/DorisConf.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/options/DorisConfBuilder.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/rest/Carrier.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/rest/DorisLoadClient.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/rest/DorisStreamLoad.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/sink/DorisSinkFactory.java
chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/table/DorisDynamicTableFactory.java

I submitted a pr and changed the load format of doris to json, so as to avoid the problem of data segmentation failure caused by the field delimiter parameter.

Changed the load format of doris to json.

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/sink/DynamicPreparedStmt.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/sink/PreparedStmtProxy.java

mysql create ddl：
CREATE DATABASE `flinkx` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */;
create table kuaidi
(
kuaidi_name varchar(20),
product_id  varchar(100)
);
create table result
(
kuaidi_name varchar(20),
count       int,
primary key (kuaidi_name)
);
INSERT INTO flinkx.kuaidi (kuaidi_name, product_id) VALUES ('申通', '1');
INSERT INTO flinkx.kuaidi (kuaidi_name, product_id) VALUES ('顺丰', '2');
INSERT INTO flinkx.kuaidi (kuaidi_name, product_id) VALUES ('中通', '3');
INSERT INTO flinkx.kuaidi (kuaidi_name, product_id) VALUES ('中通', '1');
flinkx.sql:
CREATE TABLE kuaidi
(
product_id string,
kuaidi_name string
) WITH (
'connector' = 'mysql-x',
'url' = 'jdbc:mysql://localhost:3306/flinkx?useCursorFetch=true&fetchSize=1000&useUnicode=true&characterEncoding=UTF-8', …

[fix#827][jdbc] jdbc PreparedStmtProxy can't resolve DELETE statement.this is make flink retraction failed.

---

chunjun-connectors/chunjun-connector-influxdb/src/main/java/com/dtstack/chunjun/connector/influxdb/converter/InfluxdbColumnConverter.java
chunjun-connectors/chunjun-connector-influxdb/src/main/java/com/dtstack/chunjun/connector/influxdb/source/InfluxdbInputFormat.java

#864  Influxdb convert the wrong value of 'time'.

[hotfix-864][influxdb] Influxdb convert the wrong value of 'time'.

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/lookup/provider/DruidDataSourceProvider.java

[hotfix-866][jdbc]  password 为空导致的认证失败

---

chunjun-connectors/chunjun-connector-hbase-1.4/src/main/java/com/dtstack/chunjun/connector/hbase14/sink/HBase14SinkFactory.java
chunjun-connectors/chunjun-connector-hbase-1.4/src/main/java/com/dtstack/chunjun/connector/hbase14/source/HBase14SourceFactory.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcInputFormat.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/util/SqlUtil.java
chunjun-connectors/chunjun-connector-jdbc-base/src/test/java/com/dtstack/chunjun/connector/jdbc/source/JdbcInputFormatTest.java
chunjun-core/src/main/java/com/dtstack/chunjun/element/column/ArrayColumn.java

#893 range split strategy support all numeric type

[feat-#893][jdbc]range split strategy support all numeric type

---

chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/source/HdfsDynamicTableSource.java
chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/table/HdfsDynamicTableFactory.java

#846 
HDFS obtains partition information in DDL
@FlechazoW @zoudaokoulife

[feat-#846][hdfs]hdfs sql support partitionColumn

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcInputFormat.java
chunjun-connectors/chunjun-connector-pgwal/src/main/java/com/dtstack/chunjun/connector/api/DatabaseBaseRichInputFormat.java
chunjun-core/src/main/java/com/dtstack/chunjun/metrics/BigIntegerAccumulator.java

Correct spelling mistakes BigIntegerAccmulator -> BigIntegerAccumulator
#906

[hotfix-#906][typo]Correct spelling mistakes 

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcInputFormat.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/util/SqlUtil.java
chunjun-connectors/chunjun-connector-postgresql/src/main/java/com/dtstack/chunjun/connector/postgresql/source/PostgresqlInputFormat.java

1.rename jdbcInputFormat#queryStartLocation to jdbcInputFormat#queryPollingWithoutStartLocation
2.The Polling mode concatenates the Order BY statement when startLocation is set
3.Optimizing duplicate code
#764

[hotfix-#764][jdbc]fix duplicate data occurred when use jdbc polling

---

chunjun-core/src/main/java/com/dtstack/chunjun/conf/SyncConf.java

issues :  https://github.com/DTStack/chunjun/issues/899

[hotfix-#899][conf] fix config check error

---

chunjun-connectors/chunjun-connector-clickhouse/src/main/java/com/dtstack/chunjun/connector/clickhouse/source/ClickhouseInputFormat.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/conf/JdbcConf.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/dialect/JdbcDialect.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcInputFormat.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcInputFormatBuilder.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcInputSplit.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcSourceFactory.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/distribute/DistributedJdbcInputFormat.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/distribute/DistributedJdbcInputSplit.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/util/SqlUtil.java
chunjun-connectors/chunjun-connector-jdbc-base/src/test/java/com/dtstack/chunjun/connector/jdbc/source/JdbcInputFormatTest.java

[feat-#914][jdbcSplit] jdbc rangeSplitStrategy extension

---

bin/chunjun-kubernetes-application.sh
bin/chunjun-kubernetes-session.sh
bin/chunjun-local.sh
bin/chunjun-standalone.sh
bin/chunjun-yarn-perjob.sh
bin/chunjun-yarn-session.sh
bin/submit.sh

提供一些脚本，用于减少在不同模式下任务提交需要传入的参数，只需要传递-job和-confProp即可。
其他参数如flink配置文件和hadoop配置文件，通过FLINK_HOME/HADOOP_HOME等参数预先设定。
例如：
在local 模式
```bash
bash chunjun-local.sh -job ../chunjun-examples/json/stream/stream.json
```
在standalone模式
```bash
bash chunjun-standalone.sh -job ../chunjun-examples/json/stream/stream.json
```
启动效果
```
% bash local.sh -job ../chunjun-examples/json/stream/stream.json
CHUNJUN_HOME is auto set  /Users/admin/fsdownload/chunjun-dist
FLINK_HOME is /Users/admin/flink-1.12.4
HADOOP_HOME is /Users/admin/hadoop
ChunJun starting ...
2022-06-09 14:43:37.128 [main] INFO  com.dtstack.chunjun.Main  - ------------program params-------------------------
2022-06-09 14:43:37.165 [main] INFO  com.dtstack.chunjun.Main  - -flinkLibDir
2022-06-09 14:43:37.166 [main] INFO  com.dtstack.chunjun.Main …
```

provided some shell scripts for reducing parameters to submit a job

---

chunjun-examples/json/stream/stream.json

Removes timestamp field to avoid problems caused by timestamp precision @FlechazoW 
#926

[hotfix-#926][example]Remove timestamp field in stream.json

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/sink/DynamicPreparedStmt.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/sink/JdbcDynamicTableSink.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/sink/PreparedStmtProxy.java
chunjun-examples/json/logminer/logminer_stream_insert_mode.json

sync mode Logminer Delete and Insert Statement instead of Upsert Statement.

[hotfix-#960][jdbc] sync mode logminer Delete and Insert Statement instead of Upsert Statement.

---

chunjun-connectors/chunjun-connector-binlog/src/main/java/com/dtstack/chunjun/connector/binlog/inputformat/BinlogInputFormat.java
chunjun-examples/json/binlog/binlog_stream.json
docs/connectors-en/binlog/binlog-source.md
docs/connectors/binlog/binlog-source.md

[doc-#978][docs-connector-binlog] update other 'journal-name' in text

[doc-#978][docs-connector-binlog] update other 'journal-name' in text

---

chunjun-connectors/chunjun-connector-redis/src/main/java/com/dtstack/chunjun/connector/redis/converter/RedisColumnConverter.java
chunjun-connectors/chunjun-connector-redis/src/main/java/com/dtstack/chunjun/connector/redis/converter/RedisRowConverter.java
chunjun-connectors/chunjun-connector-redis/src/main/java/com/dtstack/chunjun/connector/redis/enums/RedisDataMode.java
chunjun-connectors/chunjun-connector-redis/src/main/java/com/dtstack/chunjun/connector/redis/enums/RedisDataType.java
chunjun-connectors/chunjun-connector-redis/src/main/java/com/dtstack/chunjun/connector/redis/lookup/RedisAllTableFunction.java

Redis Lookup plugin will throw an error when query fractional field not all fields in redis hash data.

[hotfix-#1029][redis] Fix Redis Lookup Connector.

---

chunjun-connectors/chunjun-connector-oracle/src/main/java/com/dtstack/chunjun/connector/oracle/converter/OracleRawTypeConverter.java

Fixed Oracle RAW Type Apply To Flink Type is TimeStamp ERROR, Now Oracle RAW Type Apply To Flink Type is BYTES

[hotfix-816][flinkx-connector-oracle] Fixed Oracle RAW Type Apply To Flink Type is TimeStamp ERROR

---

chunjun-connectors/chunjun-connector-rocketmq/pom.xml
chunjun-connectors/chunjun-connector-rocketmq/src/main/java/com/dtstack/chunjun/connector/rocketmq/conf/RocketMQConf.java
chunjun-connectors/chunjun-connector-rocketmq/src/main/java/com/dtstack/chunjun/connector/rocketmq/converter/RocketMQRowConverter.java
chunjun-connectors/chunjun-connector-rocketmq/src/main/java/com/dtstack/chunjun/connector/rocketmq/source/RocketMQScanTableSource.java
chunjun-connectors/chunjun-connector-rocketmq/src/main/java/com/dtstack/chunjun/connector/rocketmq/source/RocketMQSourceFunction.java
chunjun-connectors/chunjun-connector-rocketmq/src/main/java/com/dtstack/chunjun/connector/rocketmq/source/RunningChecker.java
chunjun-connectors/chunjun-connector-rocketmq/src/main/java/com/dtstack/chunjun/connector/rocketmq/source/deserialization/KeyValueDeserializationSchema.java
chunjun-connectors/chunjun-connector-rocketmq/src/main/java/com/dtstack/chunjun/connector/rocketmq/source/deserialization/RowKeyValueDeserializationSchema.java
chunjun-connectors/chunjun-connector-rocketmq/src/main/java/com/dtstack/chunjun/connector/rocketmq/source/watermark/WaterMarkForAll.java
chunjun-connectors/chunjun-connector-rocketmq/src/main/java/com/dtstack/chunjun/connector/rocketmq/source/watermark/WaterMarkPerQueue.java
chunjun-connectors/chunjun-connector-rocketmq/src/main/java/com/dtstack/chunjun/connector/rocketmq/table/RocketMQDynamicTableFactory.java
chunjun-connectors/chunjun-connector-rocketmq/src/main/java/com/dtstack/chunjun/connector/rocketmq/table/RocketMQOptions.java
chunjun-connectors/chunjun-connector-rocketmq/src/main/java/com/dtstack/chunjun/connector/rocketmq/utils/RetryUtil.java
chunjun-connectors/chunjun-connector-rocketmq/src/main/java/com/dtstack/chunjun/connector/rocketmq/utils/RocketMQUtils.java
chunjun-connectors/chunjun-connector-rocketmq/src/main/resources/services/org.apache.flink.table.factories.Factory
chunjun-connectors/pom.xml
chunjun-examples/sql/rocketmq/rocketmq_stream.sql
docs_zh/ChunJun连接器/rocketmq/rocketmq-source.md

Fixes # ([1039](https://github.com/DTStack/chunjun/issues/1039)).

[feat-1039][rocketmq] add rocketmq table source.

---

bin/chunjun-standalone.sh
bin/submit.sh

fix the bug of submision in local mode and standalone mode
Fixes # 1043.
clear environment config and submit job in local mode 
```
export FLINK_HOME=
export HADOOP_HOME=
bash $CHUNJUN_HOME/bin/chunjun-local.sh  -job $CHUNJUN_HOME/chunjun-examples/json/stream/stream.json
```

[hotfix-#1043][bin] allow user to submit job in local mode

---

docs_zh/快速开始.md

[doc-#1046][quickstart]fix standalone command error

---

CONTRIBUTING.md
README.md
README_CH.md

[readme] Update README.md and add CONTRIBUTING.md

---

chunjun-connectors/chunjun-connector-hive/src/main/java/com/dtstack/chunjun/connector/hive/sink/HiveOutputFormat.java

Replace the call order of HDFSOutputFormat Close and finalizeGlobal
#1052

[hotfix-#1052][hive] Fix the data loss problem of HiveWriter

---

docs_zh/ChunJun连接器/ftp/ftp-sink.md
docs_zh/ChunJun连接器/ftp/ftp-source.md

[docs][ftp] add ftp docs

---

chunjun-connectors/chunjun-connector-greenplum/src/main/java/com/dtstack/chunjun/connector/greenplum/sink/GreenplumSinkFactory.java
chunjun-connectors/chunjun-connector-postgresql/src/main/java/com/dtstack/chunjun/connector/postgresql/sink/PostgresOutputFormat.java
chunjun-connectors/chunjun-connector-postgresql/src/main/java/com/dtstack/chunjun/connector/postgresql/sink/PostgresqlSinkFactory.java

Fix the issue of throwing connection cast-exception when use greenplum-writer.
Fixes # (1119).

[hotfix-#1119][pgsql] Connection cast-exception when use greenplum sink.

---

chunjun-core/pom.xml

[hotfix-#1124][core] core module git-commit plugin not removed, cause compile and run error. 

---

bin/submit.sh

fix the problem1:  when invoking a starting script such as chunjun-yarn-perjob.sh with the correct CHUNJUN_HOME env var, chunjun program fails cause "cd XXX/../chunjun_dist not found"
fix the problem2: when invoking a starting script such as chunjun-yarn-perjob.sh with the correct CHUNJUN_HOME env var, chunjun program can not load right classpath because of the wrong classpath path setting "xxx/chunjun-dist/../lib“

[hotfix-simple][#fix-bin]#fix-commit

---

chunjun-connectors/chunjun-connector-hive/src/main/java/com/dtstack/chunjun/connector/hive/util/HiveDbUtil.java

fix load hive jdbc dirver dead lock when parll load with mysql jdbc
Fixes # ([#1158 ](https://github.com/DTStack/chunjun/issues/1158)).

[hotfix-1158] fix load hive jdbc dirver dead lock when parll load with mysql jdbc

---

chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/handler/FtpHandler.java
chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/handler/IFtpHandler.java
chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/handler/SftpHandler.java
chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/sink/FtpOutputFormat.java
chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/source/FtpInputFormat.java

Fix the issue that the connections of SFTP are not released when task failed.
Fixes #1210 .

[hotfix-#1210][ftp] Fix the issue that the connections of SFTP are not released when task failed.

---

chunjun-clients/src/main/resources/log4j.properties

Error message of log4j raised while we submitted job from client side.
error message:
```
log4j:ERROR Could not find value for key log4j.appender.logfile
log4j:ERROR Could not instantiate appender named "logfile".
```
since we haven't define any configuration of logfile in log4j properties and we can't modify this file, it can be deleted.

[hotfix][clients] avoid unnecessary error message of logfile.

---

chunjun-connectors/chunjun-connector-sybase/pom.xml
chunjun-connectors/chunjun-connector-sybase/src/main/java/com/dtstack/chunjun/connector/sybase/converter/SybaseColumnConverter.java
chunjun-connectors/chunjun-connector-sybase/src/main/java/com/dtstack/chunjun/connector/sybase/converter/SybaseRawTypeConverter.java
chunjun-connectors/chunjun-connector-sybase/src/main/java/com/dtstack/chunjun/connector/sybase/dialect/SybaseDialect.java
chunjun-connectors/chunjun-connector-sybase/src/main/java/com/dtstack/chunjun/connector/sybase/source/SybaseSourceFactory.java
chunjun-connectors/chunjun-connector-sybase/src/main/java/com/dtstack/chunjun/connector/sybase/table/SybaseDynamicTableFactory.java
chunjun-connectors/chunjun-connector-sybase/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
chunjun-connectors/pom.xml
chunjun-core/src/main/java/com/dtstack/chunjun/metrics/AccumulatorCollector.java
chunjun-core/src/main/java/com/dtstack/chunjun/util/TelnetUtil.java
chunjun-examples/json/sybase/sybase_stream.json
chunjun-local-test/pom.xml
docs_zh/ChunJun连接器/sybase/sybase-source.md

[Feature][sybase] add sybase reader plugin #1244

[feat-#1244][sybase] add sybase reader plugin

---

chunjun-connectors/chunjun-connector-hdfs/pom.xml
chunjun-connectors/chunjun-connector-s3/pom.xml
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/conf/S3Conf.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/converter/S3ColumnConverter.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/converter/S3RawConverter.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/converter/S3RowConverter.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/sink/MyPartETag.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/sink/S3DynamicTableSink.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/sink/S3OutputFormat.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/sink/S3OutputFormatBuilder.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/sink/S3SinkFactory.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/source/S3DynamicTableSource.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/source/S3InputFormat.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/source/S3InputFormatBuilder.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/source/S3InputSplit.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/source/S3SourceFactory.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/table/S3DynamicTableFactory.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/table/options/S3Options.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/util/ReaderUtil.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/util/S3SimpleObject.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/util/S3Util.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/util/WriterUtil.java
chunjun-connectors/chunjun-connector-s3/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
chunjun-connectors/pom.xml
chunjun-examples/json/s3/ftp_s3.json
chunjun-examples/sql/s3/s3_stream.sql
chunjun-local-test/pom.xml
docs_zh/ChunJun连接器/s3/s3_sink.md
docs_zh/ChunJun连接器/s3/s3_source.md

add s3 reader and writer plugin #1251

[feat-#1251][s3] add s3 reader and writer plugin

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/util/JdbcUtil.java
chunjun-connectors/chunjun-connector-vertica11/pom.xml
chunjun-connectors/chunjun-connector-vertica11/src/main/java/com/dtstack/chunjun/connector/vertica11/conf/Vertica11LookupConf.java
chunjun-connectors/chunjun-connector-vertica11/src/main/java/com/dtstack/chunjun/connector/vertica11/converter/Vertica11ColumnConverter.java
chunjun-connectors/chunjun-connector-vertica11/src/main/java/com/dtstack/chunjun/connector/vertica11/converter/Vertica11RawTypeConverter.java
chunjun-connectors/chunjun-connector-vertica11/src/main/java/com/dtstack/chunjun/connector/vertica11/converter/Vertica11RowConverter.java
chunjun-connectors/chunjun-connector-vertica11/src/main/java/com/dtstack/chunjun/connector/vertica11/dialect/Vertica11Dialect.java
chunjun-connectors/chunjun-connector-vertica11/src/main/java/com/dtstack/chunjun/connector/vertica11/lookup/Vertica11LruTableFunction.java
chunjun-connectors/chunjun-connector-vertica11/src/main/java/com/dtstack/chunjun/connector/vertica11/lookup/options/Vertica11LookupOptions.java
chunjun-connectors/chunjun-connector-vertica11/src/main/java/com/dtstack/chunjun/connector/vertica11/lookup/provider/Vertica11DataSourceProvider.java
chunjun-connectors/chunjun-connector-vertica11/src/main/java/com/dtstack/chunjun/connector/vertica11/sink/Vertica11OutputFormat.java
chunjun-connectors/chunjun-connector-vertica11/src/main/java/com/dtstack/chunjun/connector/vertica11/sink/Vertica11SinkFactory.java
chunjun-connectors/chunjun-connector-vertica11/src/main/java/com/dtstack/chunjun/connector/vertica11/source/Vertica11DynamicTableSource.java
chunjun-connectors/chunjun-connector-vertica11/src/main/java/com/dtstack/chunjun/connector/vertica11/table/Vertica11DynamicTableFactory.java
chunjun-connectors/chunjun-connector-vertica11/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
chunjun-connectors/pom.xml
chunjun-examples/json/vertica11/hive_vertica11.json
chunjun-examples/json/vertica11/oracle_vertica11.json
chunjun-examples/sql/vertica11/kafka_vertica11_sink.sql
chunjun-examples/sql/vertica11/lookup/kafka_lookup_vertica.sql
chunjun-local-test/pom.xml

add vertica11 sink plugin #1249

[feat-#1249][vertica11] add vertica11 sink plugin

---

chunjun-connectors/chunjun-connector-kudu/src/main/java/com/dtstack/chunjun/connector/kudu/source/KuduInputFormat.java
chunjun-connectors/chunjun-connector-kudu/src/main/java/com/dtstack/chunjun/connector/kudu/source/KuduInputFormatBuilder.java
chunjun-connectors/chunjun-connector-kudu/src/main/java/com/dtstack/chunjun/connector/kudu/table/KuduDynamicTableSink.java
chunjun-connectors/chunjun-connector-kudu/src/main/java/com/dtstack/chunjun/connector/kudu/table/KuduDynamicTableSource.java

The SQL mode should directly use the rowType information in tableSchema, and no mapping is required

[hotfix-#1256][kudu]Fix SQLMode datatype mapping

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/conf/JdbcConf.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/dialect/JdbcDialect.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcDynamicTableSource.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcInputFormat.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcInputFormatBuilder.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcSourceFactory.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/util/SqlUtil.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/util/key/DateTypeUtil.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/util/key/KeyUtil.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/util/key/NumericTypeUtil.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/util/key/TimestampTypeUtil.java
chunjun-connectors/chunjun-connector-jdbc-base/src/test/java/com/dtstack/chunjun/connector/jdbc/source/JdbcInputFormatTest.java
chunjun-connectors/chunjun-connector-mysql/src/main/java/com/dtstack/chunjun/connector/mysql/converter/MysqlRawTypeConverter.java
chunjun-connectors/chunjun-connector-oracle/src/main/java/com/dtstack/chunjun/connector/oracle/dialect/OracleDialect.java
chunjun-connectors/chunjun-connector-oracle/src/main/java/com/dtstack/chunjun/connector/oracle/source/OracleInputFormat.java
chunjun-connectors/chunjun-connector-oracle/src/main/java/com/dtstack/chunjun/connector/oracle/util/increment/OracleTimestampTypeUtil.java
chunjun-connectors/chunjun-connector-sqlserver/src/main/java/com/dtstack/chunjun/connector/sqlserver/dialect/SqlserverDialect.java
chunjun-connectors/chunjun-connector-sqlserver/src/main/java/com/dtstack/chunjun/connector/sqlserver/source/SqlserverInputFormat.java
chunjun-connectors/chunjun-connector-sqlserver/src/main/java/com/dtstack/chunjun/connector/sqlserver/util/SqlUtil.java
chunjun-connectors/chunjun-connector-sqlserver/src/main/java/com/dtstack/chunjun/connector/sqlserver/util/increment/SqlserverTimestampTypeUtil.java
chunjun-e2e/src/test/java/com/dtstack/chunjun/connector/containers/emqx/EmqxContainer.java
chunjun-e2e/src/test/java/com/dtstack/chunjun/connector/test/standalone/emqx/EmqxSyncE2eITCase.java

…estoreColumn and splitPk
1.Separate the relationship between incrementColumn with RestoreColumn and splitPk
2.Use keyUtil to handle data conversion between incrementColumn/splitPk/restoreColumn and StartLocation/EndLocation/state

[feat][jdbc] Add keyUtil to handle special columns

---

chunjun-core/src/main/java/com/dtstack/chunjun/element/column/TimestampColumn.java

Type casting failed because of an import error

[hotfix][column]Fix the issue of timestampColumn convert to long error

---

chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/sink/BaseHdfsOutputFormat.java

fix:HdfsOrcOutputFormat can't get fullColumnType or Name from HdfsConf https://github.com/DTStack/chunjun/issues/987

[hotfix-#987] [chunjun-connector-hdfs] fixed HdfsOrcOutputFormat can't get fullColumnType or fullColumnName from HdfsConf

---

chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/sink/FtpOutputFormat.java
chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/sink/FtpOutputFormatBuilder.java
chunjun-core/src/main/java/com/dtstack/chunjun/sink/format/FileOutputFormatBuilder.java

[hotfix] ftp writer format null

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/util/JdbcUtil.java

use wrong about the size of config column and metadata columns size
#1289

[hotfix-#1289][chunjun-connector-jdbc-base] change column size used

---

chunjun-connectors/chunjun-connector-kafka/pom.xml
chunjun-connectors/chunjun-connector-starrocks/pom.xml

There are 1 security vulnerabilities found in com.alibaba:fastjson 1.2.79
- [CVE-2022-25845](https://www.oscs1024.com/hd/CVE-2022-25845)
Upgrade com.alibaba:fastjson from 1.2.79 to 1.2.83 for vulnerability fix

fix(sec): upgrade com.alibaba:fastjson to 1.2.83

---

chunjun-connectors/chunjun-connector-hdfs/pom.xml

There are 1 security vulnerabilities found in org.apache.hive:hive-exec 3.1.1
- [CVE-2021-34538](https://www.oscs1024.com/hd/CVE-2021-34538)
Upgrade org.apache.hive:hive-exec from 3.1.1 to 3.1.3 for vulnerability fix

fix(sec): upgrade org.apache.hive:hive-exec to 3.1.3

---

chunjun-connectors/chunjun-connector-s3/pom.xml

There are 1 security vulnerabilities found in com.amazonaws:aws-java-sdk-s3 1.11.1001
- [CVE-2022-31159](https://www.oscs1024.com/hd/CVE-2022-31159)
Upgrade com.amazonaws:aws-java-sdk-s3 from 1.11.1001 to 1.12.261 for vulnerability fix

fix(sec): upgrade com.amazonaws:aws-java-sdk-s3 to 1.12.261

---

chunjun-connectors/chunjun-connector-s3/pom.xml

There are 1 security vulnerabilities found in com.fasterxml.jackson.dataformat:jackson-dataformat-cbor 2.9.10
- [CVE-2020-28491](https://www.oscs1024.com/hd/CVE-2020-28491)
Upgrade com.fasterxml.jackson.dataformat:jackson-dataformat-cbor from 2.9.10 to 2.11.4 for vulnerability fix

fix(sec): upgrade com.fasterxml.jackson.dataformat:jackson-dataformat-cbor to 2.11.4

---

chunjun-connectors/chunjun-connector-ftp/pom.xml

There are 1 security vulnerabilities found in com.jcraft:jsch 0.1.51
- [CVE-2016-5725](https://www.oscs1024.com/hd/CVE-2016-5725)
Upgrade com.jcraft:jsch from 0.1.51 to 0.1.54 for vulnerability fix

fix(sec): upgrade com.jcraft:jsch to 0.1.54

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/conf/JdbcConf.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcInputFormat.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcInputFormatBuilder.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcInputSplit.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/util/JdbcUtil.java
chunjun-core/src/main/java/com/dtstack/chunjun/constants/Metrics.java
chunjun-core/src/main/java/com/dtstack/chunjun/metrics/AccumulatorCollector.java

… pollingMode starts with the maximum value of the incrementColumn
Set the parameter 'pollingFromMax=true' so that the pollingMode starts with the maximum value of the incrementColumn
#1300

[feat][jdbc-#1300]add parameter pollingFromMax

---

chunjun-connectors/chunjun-connector-jdbc-base/pom.xml
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/conf/CdcConf.java
chunjun-connectors/chunjun-connector-kafka/src/test/java/com/dtstack/chunjun/connector/kafka/sink/KafkaSinkFactoryTest.java
chunjun-connectors/chunjun-connector-kafka/src/test/java/com/dtstack/chunjun/connector/kafka/source/KafkaSourceFactoryTest.java
chunjun-connectors/chunjun-connector-mysqlcdc/pom.xml
chunjun-connectors/chunjun-connector-mysqlcdc/src/main/java/com/dtstack/chunjun/connector/mysqlcdc/converter/MysqlCdcRawTypeConverter.java
chunjun-connectors/chunjun-connector-mysqlcdc/src/main/java/com/dtstack/chunjun/connector/mysqlcdc/source/MysqlCdcSourceFactory.java
chunjun-connectors/chunjun-connector-mysqlcdc/src/main/java/com/dtstack/chunjun/connector/mysqlcdc/source/MysqlcdcSourceFactory.java
chunjun-connectors/pom.xml
chunjun-core/src/test/java/com/dtstack/chunjun/conf/SyncConfTest.java
chunjun-examples/json/mysqlcdc/mysql_mysql_cdc_transform.json
chunjun-local-test/pom.xml
pom.xml

[Feature][CDC]  support mysql cdc

---

chunjun-clients/src/main/java/com/dtstack/chunjun/client/standalone/StandaloneClusterClientHelper.java

…m standalone-jobGraph
Remove classpath, userJars, and Artifacts from jobmanager because the chunjun-dist related package is already in the flink/lib directory
#1338

[feat][standalone-#1338]Remove classpath, userJars, and Artifacts from jobgraph

---

chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/sink/BaseHdfsOutputFormat.java
chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/sink/HdfsOrcOutputFormat.java
chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/sink/HdfsParquetOutputFormat.java
chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/sink/HdfsTextOutputFormat.java

修复写入HDFS后的路径问题。使本地调试时能正常写hdfs。
Fixes # (1336).

[Improve][HDFS][#1336] Fix the path problem of writing to HDFS.

---

chunjun-ddl/chunjun-ddl-base/pom.xml

[HOTFIX][DDL-Base] Fix the error that the antrun-maven plugin moves the miss target class.
None.

[HOTFIX][DDL-Base] Fix the error that the antrun-maven plugin moves the miss target class.

---

chunjun-connectors/chunjun-connector-mysql/src/main/java/com/dtstack/chunjun/connector/mysql/dialect/MysqlDialect.java
chunjun-e2e/src/test/java/com/dtstack/chunjun/connector/containers/mysql/MysqlBaseContainer.java

…cannot be capitalized by default.

[hotfix][mysql][e2e] mysql silent unclassified size copy,table names cannot be capitalized by default.

---

README.md
README_CH.md

add notes about starting a Flink standalone cluster with chunjun jars
copy from https://github.com/DTStack/chunjun/pull/1169

[doc] add notes about starting a Flink standalone cluster with chunjun jars

---

chunjun-connectors/chunjun-connector-binlog/pom.xml
chunjun-connectors/chunjun-connector-clickhouse/pom.xml
chunjun-connectors/chunjun-connector-dm/pom.xml
chunjun-connectors/chunjun-connector-file/pom.xml
chunjun-connectors/chunjun-connector-hdfs/pom.xml
chunjun-connectors/chunjun-connector-mongodb/pom.xml
chunjun-connectors/chunjun-connector-oceanbase/pom.xml
chunjun-connectors/chunjun-connector-oceanbasecdc/pom.xml
chunjun-connectors/chunjun-connector-pgwal/pom.xml
chunjun-connectors/chunjun-connector-saphana/pom.xml
chunjun-connectors/chunjun-connector-solr/pom.xml
chunjun-connectors/chunjun-connector-sqlservercdc/pom.xml

[Hotfix][Connector] Fix the jvm throws "java.lang.SecurityException: Invalid signature file digest for Manifest main attributes" error.
None.

[Hotfix][Connector] Fix the jvm throws java.lang.SecurityException

---

chunjun-connectors/chunjun-connector-emqx/src/main/java/com/dtstack/chunjun/connector/emqx/converter/EmqxColumnConverter.java
chunjun-connectors/chunjun-connector-kafka/src/main/java/com/dtstack/chunjun/connector/kafka/converter/KafkaColumnConverter.java
chunjun-connectors/chunjun-connector-kafka/src/main/java/com/dtstack/chunjun/connector/kafka/option/KafkaOptions.java
chunjun-core/src/main/java/com/dtstack/chunjun/decoder/ValueDecoder.java
chunjun-core/src/main/java/com/dtstack/chunjun/util/MapUtil.java
chunjun-core/src/test/java/com/dtstack/chunjun/decoder/ValueDecoderTest.java

Add value decoder, for the purpose that we only need value
#1353

[feature-#1353][kafka-connector] add value deocder

---

README.md
README_CH.md

增加sh脚本中\r问题的修复命令
Fixes # (1402).
- [x ] I have a meaningful commit message (including the issue id, **the template of commit message is '[label-type-#issue-id][fixed-module] a meaningful commit message.'**)
- [x ] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [x ] I have made corresponding changes to the documentation.
- [ x] I have checked my code and corrected any misspellings.
- [x ] My commit is only one. (If there are multiple commits, you can use 'git squash' to compress multiple commits into one.)

fix BUG #1402,fix '\r' problems caused by windows

---

chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/converter/HdfsTextColumnConverter.java
chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/source/HdfsTextInputFormat.java
chunjun-connectors/chunjun-connector-oraclelogminer/src/main/java/com/dtstack/chunjun/connector/oraclelogminer/listener/LogMinerListener.java

1. hdfs connector：
1.1 make  column converter can dealing with null value of column correctly 
1.2 make the inputformatter can split correctly text row by seperate operator that consists of multiple characters
2.oracle log miner connector：
2.1 when setting the enableFetchAll to true , the job would generate table ddl statement no mater whether the initialTableStructure parameter is set to true. Now add a if statement for controlling this feature.

[hotfix][hdfs and oraclelogminer] Solved the problem of splitting columns and handling null values in hdfs components

---

bin/submit.sh
chunjun-assembly/pom.xml
chunjun-assembly/src/main/assembly/assembly.xml
chunjun-clients/pom.xml
chunjun-connectors/chunjun-connector-hdfs/pom.xml
chunjun-connectors/chunjun-connector-hive/pom.xml
chunjun-core/pom.xml
chunjun-ddl/chunjun-ddl-mysql/pom.xml
chunjun-restore/chunjun-restore-mysql/pom.xml

bsh,xml-resolver 的默认版本无法直接访问到，更新版本到可访问版本。本地maven 打包测试通过。
Fixes # (1398).
- [] I have commented my code, particularly in hard-to-understand areas.
- [] I have made corresponding changes to the documentation.

fix BUG #1398,fix bsh,xml-resolver default version cannot access

---

chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/converter/HdfsTextColumnConverter.java

fix the issue: The hdfs connector cannot read correctly from the hfds files which generated by the hdfs connector itself.
When hdfs connector writing data to hdfs, null value of a  column is set as a member of a  String array that is a data row`s output, eg, data[0] = null,  that results in "null" string value would be written into the hdfs text files.
solution: 
null value is set to '\N' for hive specification so that hdfs connector can read from the output.

[hotfix][hdfs]when writing to hfds,null value is set to '\N'

---

chunjun-connectors/chunjun-connector-hive/src/main/java/com/dtstack/chunjun/connector/hive/util/PathConverterUtil.java

add function to try to transform a valid format of hive table name from source table name that is not compatible with hive specification.

[hostfix][hive] add HIVe table check and  correct function

---

chunjun-connectors/chunjun-connector-hive/src/main/java/com/dtstack/chunjun/connector/hive/util/PathConverterUtil.java

这个方法应该在循环外调用才正确。不然会将${table}替换掉

[hotfix][hive] fix bug for try get correct hive table funciton

---

chunjun-connectors/chunjun-connector-mysqlcdc/pom.xml

com.ververica.cdc.connectors.mysql.table.MySqlTableSourceFactory not merge in META-INF/services/org.apache.flink.table.factories.Factory when maven package

Fix:mysql-cdc can't run in sql mode

---

chunjun-connectors/chunjun-connector-clickhouse/src/main/java/com/dtstack/chunjun/connector/clickhouse/source/ClickhouseInputFormat.java

[Fixes # (issue).](https://github.com/DTStack/chunjun/issues/1449)

[hotfix-#1449][ClickHouse] fix ClickHouse source null pointer problem

---

chunjun-connectors/chunjun-connector-hbase-base/src/main/java/com/dtstack/chunjun/connector/hbase/FunctionParser.java
chunjun-connectors/chunjun-connector-hbase-base/src/main/java/com/dtstack/chunjun/connector/hbase/converter/HBaseColumnConverter.java

As we know,we can use 'rowkeyExpress' in hbasecolumn. and chunjun will replace the value in "$()",this pr can support column field also has that function.
我们知道在hbase-connector中可以使用'rowkeyExpress'当做主键表达式，chunjun会用字段值替换在"$()"中的字段名称，这个pr可以支持 列字段 同样有这个功能。
。。。
"rowkeyExpress": "$(rowkey)",
"column": [
{"type": "string","name":"v:cid"},
{"type": "string","name":"rowkey"},
{"type": "string","name":"v:c_30_i_$(cid)"},
{"type": "string","name":"v:c_30_c_$(cid)"},
{"type": "string","name":"v:c_30_r_$(cid)"}
]
。。。
#1451

[fix-##1451] add column replace for hbase column

---

chunjun-connectors/chunjun-connector-hbase-base/src/main/java/com/dtstack/chunjun/connector/hbase/conf/HBaseConf.java
chunjun-connectors/chunjun-connector-hbase-base/src/main/java/com/dtstack/chunjun/connector/hbase/converter/HBaseColumnConverter.java

1.If we put rowkey at column first place. Nullpointer!
如果我们吧rowkey放在列的第一位就会报空指针，判空的时候忽略了第一位
2.支持hbasesink文件的这一批数据的TTL
#1455

[feat-##1455] fix hbase bug & add hbase ttl

---

chunjun-connectors/chunjun-connector-postgresql/src/main/java/com/dtstack/chunjun/connector/postgresql/sink/PostgresOutputFormat.java

The cast is bad, only when 'rowConverter' instance of the 'JdbcColumnConverter' should cast.
Fixes # (1463).

[BugFix][Postgres][#1463] The cast is bad, only when 'rowConverter' instance of the 'JdbcColumnConverter' should cast.

---

chunjun-clients/src/main/java/com/dtstack/chunjun/client/yarn/YarnPerJobClusterClientHelper.java

[Bug- #1473 ][chunjun-clients] fix Logic error in confProp parameter processing

fix Logic error in confProp parameter processing

---

chunjun-connectors/chunjun-connector-hbase-base/src/main/java/com/dtstack/chunjun/connector/hbase/converter/HBaseColumnConverter.java

Hbase ttl is millisecond not second.
#1485

[BugFix][hbse-connector][#1485] hbase ttl millisecond not second

---

chunjun-connectors/chunjun-connector-greenplum/src/main/java/com/dtstack/chunjun/connector/greenplum/dialect/GreenplumDialect.java
chunjun-connectors/chunjun-connector-greenplum/src/main/java/com/dtstack/chunjun/connector/greenplum/sink/GreenplumOutputFormat.java
chunjun-connectors/chunjun-connector-greenplum/src/main/java/com/dtstack/chunjun/connector/greenplum/sink/GreenplumSinkFactory.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/conf/JdbcConf.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/sink/JdbcOutputFormat.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/sink/JdbcOutputFormatBuilder.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcDynamicTableSource.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcInputFormat.java
chunjun-connectors/chunjun-connector-oracle/src/main/java/com/dtstack/chunjun/connector/oracle/converter/OracleColumnConverter.java
chunjun-connectors/chunjun-connector-oracle/src/main/java/com/dtstack/chunjun/connector/oracle/source/OracleInputFormat.java
chunjun-connectors/chunjun-connector-postgresql/src/main/java/com/dtstack/chunjun/connector/postgresql/dialect/PostgresqlDialect.java
chunjun-connectors/chunjun-connector-vertica11/src/main/java/com/dtstack/chunjun/connector/vertica11/sink/Vertica11OutputFormat.java

improvement jdbc read/write performance

[feat][jdbc]improvement jdbc read/write performance

---

chunjun-connectors/chunjun-connector-http/pom.xml
chunjun-connectors/chunjun-connector-http/src/main/java/com/dtstack/chunjun/connector/http/client/CsvResponseParse.java
chunjun-connectors/chunjun-connector-http/src/main/java/com/dtstack/chunjun/connector/http/client/DefaultRestHandler.java
chunjun-connectors/chunjun-connector-http/src/main/java/com/dtstack/chunjun/connector/http/client/HttpClient.java
chunjun-connectors/chunjun-connector-http/src/main/java/com/dtstack/chunjun/connector/http/client/JsonResponseParse.java
chunjun-connectors/chunjun-connector-http/src/main/java/com/dtstack/chunjun/connector/http/client/ResponseParse.java
chunjun-connectors/chunjun-connector-http/src/main/java/com/dtstack/chunjun/connector/http/client/ResponseValue.java
chunjun-connectors/chunjun-connector-http/src/main/java/com/dtstack/chunjun/connector/http/client/RestHandler.java
chunjun-connectors/chunjun-connector-http/src/main/java/com/dtstack/chunjun/connector/http/client/TextResponseParse.java
chunjun-connectors/chunjun-connector-http/src/main/java/com/dtstack/chunjun/connector/http/client/XmlResponseParse.java
chunjun-connectors/chunjun-connector-http/src/main/java/com/dtstack/chunjun/connector/http/common/ConstantValue.java
chunjun-connectors/chunjun-connector-http/src/main/java/com/dtstack/chunjun/connector/http/common/HttpRestConfig.java
chunjun-connectors/chunjun-connector-http/src/main/java/com/dtstack/chunjun/connector/http/common/HttpUtil.java
chunjun-connectors/chunjun-connector-http/src/main/java/com/dtstack/chunjun/connector/http/converter/HttpColumnConverter.java
chunjun-connectors/chunjun-connector-http/src/main/java/com/dtstack/chunjun/connector/http/inputformat/HttpInputFormat.java
chunjun-connectors/chunjun-connector-http/src/main/java/com/dtstack/chunjun/connector/http/util/JsonPathUtil.java
chunjun-connectors/chunjun-connector-http/src/main/java/com/dtstack/chunjun/connector/http/util/XmlUtil.java

#1494 [feat-1494][http] http support array data

---

chunjun-connectors/chunjun-connector-greenplum/src/main/java/com/dtstack/chunjun/connector/greenplum/dialect/GreenplumDialect.java
chunjun-connectors/chunjun-connector-greenplum/src/main/java/com/dtstack/chunjun/connector/greenplum/sink/GreenplumOutputFormat.java
chunjun-connectors/chunjun-connector-greenplum/src/main/java/com/dtstack/chunjun/connector/greenplum/sink/GreenplumSinkFactory.java
chunjun-core/src/main/java/com/dtstack/chunjun/Main.java
chunjun-core/src/main/java/com/dtstack/chunjun/options/Options.java

…de=batch
add new option 'runMode'.  
support run sql job with batch mode when set runMode=batch
#1498

[feat-#1498][main] support run sql job with batch mode

---

chunjun-connectors/chunjun-connector-http/src/main/java/com/dtstack/chunjun/connector/http/converter/HttpColumnConverter.java

[bug][http] commonConf NullPointerException #1510

---

chunjun-connectors/chunjun-connector-http/src/main/java/com/dtstack/chunjun/connector/http/converter/HttpColumnConverter.java
chunjun-connectors/chunjun-connector-mongodb/src/main/java/com/dtstack/chunjun/connector/mongodb/converter/MongodbColumnConverter.java

fix mongodb read data not support objectId type

[hotfix-#1518][mongodb] fix mongodb read data not support objectId type

---

chunjun-assembly/src/main/assembly/assembly.xml

…aging
the chunjun-clients.jar cannot be found after packaging
[add][assembly]
```
<fileSet>
<directory>${project.parent.basedir}/chunjun-clients/target</directory>
<outputDirectory>lib</outputDirectory>
<includes>
<include>chunjun-clients.jar</include>
</includes>
</fileSet>
after run mvn clean  package -DskipTests
successfully got lib/chunjun-clients.jar
```
<br/>
<br/>

[Improvement][assembly] the chunjun-clients.jar cannot be found after packaging

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcInputFormat.java
chunjun-core/src/main/java/com/dtstack/chunjun/metrics/BigIntegerAccumulator.java

… the amount of readable data was 0
Fixed an issue where EndLocation was not set when the amount of readable data was 0
#1553

[hotfix-#1553][jdbc]Fixed endlocation not being set

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/util/SqlUtil.java

remove redundant comma of querySplitRangeSql, below sqls are the right  templates
```
"SELECT min(%s) as min_value ,max(%s) as max_value FROM (%s)tmp"
"SELECT min(%s) as min_value,max(%s) as max_value FROM %s %s"
```
[Fixes # (issue).](https://github.com/DTStack/chunjun/issues/1559)

[hotfix-#1559][jdbc-connector] remove redundant comma of querySplitRangeSql

---

chunjun-connectors/chunjun-connector-sqlserver/src/main/java/com/dtstack/chunjun/connector/sqlserver/sink/SqlserverOutputFormat.java
chunjun-local-test/src/main/java/com/dtstack/chunjun/local/test/LocalTest.java

if write column is not have identity column, not execute SET IDENTITY_INSERT %s ON
Fixes #1568 .

[hotfix-#1568][sqlserver] if write column is not have identity column, not execute SET IDENTITY_INSERT %s ON

---

chunjun-connectors/chunjun-connector-sqlservercdc/src/main/java/com/dtstack/chunjun/connector/sqlservercdc/listener/SqlServerCdcListener.java

…ilable
Reacquire a connection when it is not available
#1577

[hotfix-#1577][sqlservercdc]Reacquire when connection is closed

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcInputFormat.java
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/util/SqlUtil.java
chunjun-connectors/chunjun-connector-jdbc-base/src/test/java/com/dtstack/chunjun/connector/jdbc/source/JdbcInputFormatTest.java
chunjun-connectors/chunjun-connector-postgresql/src/main/java/com/dtstack/chunjun/connector/postgresql/source/PostgresqlInputFormat.java

fix the problem that polling sometimes may duplicate data[no.1581](https://github.com/DTStack/chunjun/issues/1581)

[hotfix-1581][jdbc-base] fix the problem that polling sometimes may duplicate data

---

chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/table/HdfsDynamicTableFactory.java

解决字段分割符转义问题, 比如``` \t``` 会被转义成``` \\t```, 导致读取数据异常，误报成脏数据问题
Fixes #1586 .

[feat-#1586][hdfs]Fixed the problem of escaping the field delimiter

---

chunjun-core/src/main/java/com/dtstack/chunjun/Main.java
chunjun-core/src/main/java/com/dtstack/chunjun/util/PrintUtil.java

解决yarn-per-job sql 模式执行不退出问题 解决大并行度时获取统计指标报错问题.
只有在 confProp '{ "chunjun.cluster.execution-mode":"NORMAL"}' 增加此配置参数后才会触发。
由于在 log.info 无法将结果输出到终端上，因此使用 System.out.println()输出。
修复完执行效果如下，
Fixes #1596

[hotfix-#1596][core] Solve the problem that yarn-per-job sql mode does not exit when executing batch jobs

---

chunjun-core/src/main/java/org/apache/flink/streaming/api/graph/StreamGraph.java

…
SQL任务中addSink方法不会设置outputFormat导致initializeGlobal、finalizeGlobal方法没有被调用
Fixes #1605

[hotfix-#1605][core] sql mode supports call initializeGlobal、finalizeGlobal

---

chunjun-core/src/main/java/com/dtstack/chunjun/sql/parser/SetStmtParser.java

解决sink.post-sql里的包含set 关键字导致sql解析错误
Fixes #1610

[hotfix-#1610][core]Fixed the sql parsing error of sink post-sql aining the set keyword

---

chunjun-connectors/chunjun-connector-hdfs/pom.xml
chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/config/HdfsConfig.java
chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/converter/HdfsTextColumnConverter.java
chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/options/HdfsOptions.java
chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/sink/BaseHdfsOutputFormat.java
chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/source/HdfsTextInputFormat.java
chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/table/HdfsDynamicTableFactory.java

解决以下问题：
优化点：
1、修复 java.io.EOFException: Unexpected end of input stream
2、排除 hadoop 相关依赖包
3、解决ClassCastException NULL空值问题
4、支持在目标目录下生成一个指定文件名的空文件，例如：_SUCCESS 空文件
5、读取时，当hdfs source中只定义一个字段时，该值是 一行nginx log的话（ 127.239.193.194 - - [14/Sep/2020:00:51:59 +0800] "GET /safe/tray.html? ），字段分割为空时，读取出来的数据缺失问题。
Fixes #1647

[feat-#1647][hdfs] Support to generate an empty file with a specified file name in the target directory, and other optimization

---

chunjun-connectors/chunjun-connector-emqx/src/main/java/com/dtstack/chunjun/connector/emqx/converter/EmqxRowConverter.java

由于>=1.13版本flink对 JsonRowDataSerializationSchema 对象内部方法做了调整；mapper对象的创建需要调用open方法；以前低版本<=1.12 直接在成员属性中直接new的；因此不会出现空指针；
参考:https://github.com/DTStack/chunjun/issues/1673
测试了MyCDC写入到MQTT正常；测试环境为Flink1.16.1版本;Hadoop版本为3.2.2

Fix EmqxRowConverter.toExternal NullPointerException

---

chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/converter/DummyInitializationContext.java
chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/converter/FtpSqlConverter.java
chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/handler/FtpHandler.java
chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/sink/FtpOutputFormat.java
chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/spliter/ConcurrentZipCompressSplit.java
chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/table/FtpDynamicTableFactory.java

1、解决 CsvRowDataDeserializationSchema objectReader 空指针问题
2、解决 ftpClient.completePendingCommand 当 inputStream 为null 读取超时问题，
3、统一 FtpOutputFormat 拼接路径使用的分割符
4、解决 ConcurrentZipCompressSplit 里初始化 FtpFileSplit 构造参数顺序问题，原因：读取的压缩包里路径不对 
Fixes #1701

[hotfix-#1701][connector][ftp] fixed Read timed out

---

chunjun-connectors/chunjun-connector-mysql/src/main/java/com/dtstack/chunjun/connector/mysql/dialect/MysqlDialect.java

Fixed a decimal type precision calculation issue in MySQL
Fixed a decimal type precision calculation issue in MySQL
https://github.com/DTStack/chunjun/issues/1756

[hotfix-1756][mysql]Fixed a decimal type precision calculation issue in MySQL

---

chunjun-connectors/chunjun-connector-starrocks/src/main/java/com/dtstack/chunjun/connector/starrocks/sink/StarRocksOutputFormat.java
chunjun-connectors/chunjun-connector-starrocks/src/main/java/com/dtstack/chunjun/connector/starrocks/streamload/StarRocksQueryVisitor.java
chunjun-connectors/chunjun-connector-starrocks/src/main/java/com/dtstack/chunjun/connector/starrocks/streamload/StreamLoadManager.java

修复sr table没有建立分区导致写入失败，但flink任务显示成功
link   #1771 (issue).

[hotfix-#1771] [connector][starrocks] The sr table was not partitioned, causing data consumption to fail but the flink task presentation to succeed

---

.idea/vcs.xml
chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/converter/HdfsOrcSyncConverter.java
chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/converter/HdfsParquetSyncConverter.java
chunjun-connectors/chunjun-connector-hdfs/src/main/java/com/dtstack/chunjun/connector/hdfs/converter/HdfsTextSyncConverter.java

[hotfix-#1795][hdfs] fix sink hdfs bug

---

chunjun-connectors/chunjun-connector-binlog/pom.xml
chunjun-connectors/chunjun-connector-greenplum/src/main/java/com/dtstack/chunjun/connector/greenplum/sink/GreenplumSinkFactory.java
chunjun-connectors/chunjun-connector-hdfs/pom.xml
chunjun-connectors/chunjun-connector-hive/pom.xml
chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/util/JdbcUtil.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/config/S3Config.java
chunjun-core/src/main/java/com/dtstack/chunjun/config/FieldConfig.java
chunjun-core/src/main/java/com/dtstack/chunjun/element/column/StringColumn.java
chunjun-core/src/main/java/com/dtstack/chunjun/typeutil/serializer/base/StringColumnSerializer.java
pom.xml

[Feature-#1787]Support hadoop 3 compilation and packaging

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/table/JdbcDynamicTableFactory.java

…
Fixes #1799 
- [] I have executed the **'mvn spotless:apply'** command to format my code.
- [] I have a meaningful commit message (including the issue id, **the template of commit message is '[label-type-#issue-id][fixed-module] a meaningful commit message.'**)

[hotfix-#1799][connector][jdbc] Fix related issues when the write mode is replace/update

---

chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/enums/CompressType.java
chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/handler/FtpHandler.java
chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/sink/FtpOutputFormat.java
chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/table/FtpDynamicTableFactory.java
chunjun-core/src/main/java/com/dtstack/chunjun/security/KerberosUtil.java

[Feature-#1842][ftp] Added compress and write mode when writing, fixed the config of sftp is null

---

chunjun-connectors/chunjun-connector-socket/src/main/java/com/dtstack/chunjun/connector/socket/converter/SocketSqlConverter.java
chunjun-connectors/chunjun-connector-socket/src/main/java/com/dtstack/chunjun/connector/socket/inputformat/SocketInputFormat.java
chunjun-connectors/chunjun-connector-socket/src/main/java/com/dtstack/chunjun/connector/socket/inputformat/SocketInputFormatBuilder.java
chunjun-connectors/chunjun-connector-socket/src/main/java/com/dtstack/chunjun/connector/socket/options/SocketOptions.java
chunjun-connectors/chunjun-connector-socket/src/main/java/com/dtstack/chunjun/connector/socket/source/SocketDynamicTableSource.java
chunjun-connectors/chunjun-connector-socket/src/main/java/com/dtstack/chunjun/connector/socket/table/SocketDynamicTableFactory.java
chunjun-connectors/chunjun-connector-socket/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory

[Feature-#1851][socket] Support reading data from socket connector in sql mode

---

chunjun-connectors/chunjun-connector-s3/pom.xml
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/config/S3Config.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/enums/CompressType.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/sink/S3DynamicTableSink.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/sink/S3OutputFormat.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/source/S3DynamicTableSource.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/source/S3InputFormat.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/table/S3DynamicTableFactory.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/table/options/S3Options.java
chunjun-connectors/chunjun-connector-s3/src/main/java/com/dtstack/chunjun/connector/s3/util/S3Util.java
chunjun-core/src/main/java/com/dtstack/chunjun/util/JsonUtil.java

[Feature-#1862][s3] Added support for reading compressed format files , writing multiple objects etc.

---

chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/client/excel/ExcelReaderExecutor.java
chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/config/FtpConfig.java
chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/extend/ftp/IFormatConfig.java
chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/iformat/ExcelFileFormat.java
chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/options/FtpOptions.java
chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/source/FtpInputFormat.java
chunjun-connectors/chunjun-connector-ftp/src/main/java/com/dtstack/chunjun/connector/ftp/table/FtpDynamicTableFactory.java

[Feature-#1889][ftp] read support column index and sheetNO

---

chunjun-connectors/chunjun-connector-gbase8s/pom.xml
chunjun-connectors/chunjun-connector-gbase8s/src/main/java/com/dtstack/chunjun/connector/gbase8s/converter/Gbase8sRawTypeConverter.java
chunjun-connectors/chunjun-connector-gbase8s/src/main/java/com/dtstack/chunjun/connector/gbase8s/dialect/Gbase8sDialect.java
chunjun-connectors/chunjun-connector-gbase8s/src/main/java/com/dtstack/chunjun/connector/gbase8s/sink/Gbase8sSinkFactory.java
chunjun-connectors/chunjun-connector-gbase8s/src/main/java/com/dtstack/chunjun/connector/gbase8s/source/Gbase8sSourceFactory.java
chunjun-connectors/chunjun-connector-gbase8s/src/main/java/com/dtstack/chunjun/connector/gbase8s/table/Gbase8sDynamicTableFactory.java
chunjun-connectors/chunjun-connector-gbase8s/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
chunjun-connectors/chunjun-connector-gbasehk/pom.xml
chunjun-connectors/chunjun-connector-gbasehk/src/main/java/com/dtstack/chunjun/connector/gbasehk/converter/GbasehkRawTypeConverter.java
chunjun-connectors/chunjun-connector-gbasehk/src/main/java/com/dtstack/chunjun/connector/gbasehk/dialect/GbasehkDialect.java
chunjun-connectors/chunjun-connector-gbasehk/src/main/java/com/dtstack/chunjun/connector/gbasehk/sink/GbasehkSinkFactory.java
chunjun-connectors/chunjun-connector-gbasehk/src/main/java/com/dtstack/chunjun/connector/gbasehk/source/GbasehkSourceFactory.java
chunjun-connectors/chunjun-connector-gbasehk/src/main/java/com/dtstack/chunjun/connector/gbasehk/table/GbasehkDynamicTableFactory.java
chunjun-connectors/chunjun-connector-gbasehk/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
chunjun-connectors/pom.xml

[Feature-#1897][gbase8s] Added gbase8s connector and gbasehk connector

---

chunjun-core/src/main/java/com/dtstack/chunjun/source/DtInputFormatSourceFunction.java
chunjun-core/src/main/java/com/dtstack/chunjun/source/format/BaseRichInputFormat.java
chunjun-core/src/main/java/com/dtstack/chunjun/throwable/ReadRecordException.java

… and when the source sends it downstream #1901

[Feature][chunjun-core] Supports capturing dirty data from the source and when the source sends it downstream #1901

---

chunjun-connectors/chunjun-connector-sqlserver/src/main/java/com/dtstack/chunjun/connector/sqlserver/table/SqlserverDynamicTableFactory.java

[hotfix-#1904][sqlserver] fixed No suitable driver found for jdbc jtds

---

chunjun-connectors/chunjun-connector-starrocks/src/main/java/com/dtstack/chunjun/connector/starrocks/options/ConstantValue.java
chunjun-connectors/chunjun-connector-starrocks/src/main/java/com/dtstack/chunjun/connector/starrocks/sink/StarRocksOutputFormat.java
chunjun-connectors/chunjun-connector-starrocks/src/main/java/com/dtstack/chunjun/connector/starrocks/sink/StarRocksSinkFactory.java
chunjun-connectors/chunjun-connector-starrocks/src/main/java/com/dtstack/chunjun/connector/starrocks/streamload/StarRocksStreamLoadVisitor.java
chunjun-core/src/main/java/com/dtstack/chunjun/sink/format/BaseRichOutputFormat.java

[hotfix-1908][chunjun-connector-starrocks] starrocks data size check

---

chunjun-connectors/chunjun-connector-gbase8s/pom.xml
chunjun-connectors/chunjun-connector-starrocks/src/main/java/com/dtstack/chunjun/connector/starrocks/sink/StarRocksOutputFormat.java
chunjun-connectors/chunjun-connector-starrocks/src/main/java/com/dtstack/chunjun/connector/starrocks/streamload/StreamLoadManager.java

[hotfix-#1911][starrocks] fixed stream load failed do not throw exception

---

chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcSourceFactory.java
chunjun-core/src/test/java/com/dtstack/chunjun/config/BaseFileConfigTest.java

[Bug][chunjun-connectors] jdbc's properties not work where jdbc's reader has set properties
